-- ============================================================
-- PRO MOD LOGBOOK — COMPREHENSIVE INCREMENTAL MIGRATION
-- ============================================================
-- Run this ONE script in the Supabase SQL Editor to fix ALL
-- missing tables, columns, indexes, and RLS policies.
--
-- Safe to run multiple times: uses IF NOT EXISTS / IF NOT EXISTS
-- on every statement.
--
-- Generated by comparing EVERY TypeScript interface, database.ts
-- converter, UI form field, and edge function payload against the
-- existing supabase_schema.sql.
-- ============================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. user_profiles — ADD MISSING user_id COLUMN
-- ============================================================
-- CRITICAL: AuthContext.tsx fetchProfile() queries .eq('user_id', userId)
-- and ensureProfile() inserts { user_id: userId }, but the table only
-- has `id` as the primary key. We add a `user_id` column that mirrors `id`.
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS user_id UUID;

-- Backfill user_id from id for any existing rows
UPDATE public.user_profiles
  SET user_id = id
  WHERE user_id IS NULL;

-- Add a default so new rows auto-populate user_id
-- (Cannot use ALTER COLUMN SET DEFAULT with IF NOT EXISTS, so wrap in DO block)
DO $$ BEGIN
  -- Only set default if not already set
  IF NOT EXISTS (
    SELECT 1 FROM pg_attrdef ad
    JOIN pg_attribute a ON a.attrelid = ad.adrelid AND a.attnum = ad.adnum
    JOIN pg_class c ON c.oid = a.attrelid
    WHERE c.relname = 'user_profiles' AND a.attname = 'user_id'
    AND pg_get_expr(ad.adbin, ad.adrelid) LIKE '%auth.uid()%'
  ) THEN
    ALTER TABLE public.user_profiles ALTER COLUMN user_id SET DEFAULT auth.uid();
  END IF;
END $$;

-- Create index on user_id for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles(user_id);

-- Add unique constraint on user_id (safe: wrapped in DO block)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_profiles_user_id_unique'
  ) THEN
    ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_user_id_unique UNIQUE (user_id);
  END IF;
EXCEPTION WHEN others THEN
  RAISE NOTICE 'user_profiles_user_id_unique constraint already exists or cannot be created: %', SQLERRM;
END $$;


-- ============================================================
-- 2. engines — ADD MISSING displacement COLUMN
-- ============================================================
-- InitialSetup.tsx writes `displacement` field when saving engines
ALTER TABLE public.engines
  ADD COLUMN IF NOT EXISTS displacement TEXT;


-- ============================================================
-- 3. setup_vendors — ADD 6 MISSING COLUMNS
-- ============================================================
-- VendorManagement.tsx Vendor interface and InitialSetup.tsx use these fields
-- that don't exist in the current schema.
ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS discount_percent NUMERIC DEFAULT 0;

ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS lead_time_days INTEGER DEFAULT 14;

ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS minimum_order NUMERIC DEFAULT 0;

ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS shipping_method TEXT;

ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE public.setup_vendors
  ADD COLUMN IF NOT EXISTS created_date TEXT;


-- ============================================================
-- 4. team_invites — CREATE MISSING TABLE
-- ============================================================
-- Used by: send-team-invite edge function, teamMembership.ts
-- The edge function inserts invites and the frontend reads them.
CREATE TABLE IF NOT EXISTS public.team_invites (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_owner_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email           TEXT NOT NULL,
  role            TEXT DEFAULT 'Crew',
  permissions     JSONB DEFAULT '["view"]'::jsonb,
  token           TEXT NOT NULL,
  status          TEXT DEFAULT 'pending',        -- pending, accepted, expired, revoked
  invited_by_name TEXT,
  team_name       TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  expires_at      TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days'),
  accepted_at     TIMESTAMPTZ
);

ALTER TABLE public.team_invites ENABLE ROW LEVEL SECURITY;

-- RLS: Team owners can manage their own invites
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Owners manage own team_invites' AND tablename = 'team_invites') THEN
    CREATE POLICY "Owners manage own team_invites"
      ON public.team_invites FOR ALL
      USING (auth.uid() = team_owner_id)
      WITH CHECK (auth.uid() = team_owner_id);
  END IF;
END $$;

-- RLS: Service role (edge functions) can also manage invites
-- The send-team-invite function uses the service role key, so it bypasses RLS.
-- But we also need a policy for users to read invites sent TO them (by email).
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view invites sent to them' AND tablename = 'team_invites') THEN
    CREATE POLICY "Users can view invites sent to them"
      ON public.team_invites FOR SELECT
      USING (
        auth.uid() = team_owner_id
        OR email = (SELECT email FROM auth.users WHERE id = auth.uid())
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_team_invites_owner    ON public.team_invites(team_owner_id);
CREATE INDEX IF NOT EXISTS idx_team_invites_token    ON public.team_invites(token);
CREATE INDEX IF NOT EXISTS idx_team_invites_email    ON public.team_invites(email);
CREATE INDEX IF NOT EXISTS idx_team_invites_status   ON public.team_invites(status);


-- ============================================================
-- 5. team_memberships — CREATE MISSING TABLE
-- ============================================================
-- Used by: AuthContext.tsx (checkTeamMembership), teamMembership.ts
-- Links a Supabase auth user to a team owner's data.
CREATE TABLE IF NOT EXISTS public.team_memberships (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_owner_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  team_member_id   TEXT,                         -- Optional link to team_members.id
  role             TEXT DEFAULT 'Crew',
  permissions      JSONB DEFAULT '["view"]'::jsonb,
  status           TEXT DEFAULT 'active',        -- active, suspended, removed
  joined_at        TIMESTAMPTZ DEFAULT NOW(),
  invite_id        UUID,                         -- Link back to team_invites.id
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.team_memberships ENABLE ROW LEVEL SECURITY;

-- Unique constraint: one membership per user per team
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'team_memberships_unique_member'
  ) THEN
    ALTER TABLE public.team_memberships
      ADD CONSTRAINT team_memberships_unique_member
      UNIQUE (team_owner_id, member_user_id);
  END IF;
EXCEPTION WHEN others THEN
  RAISE NOTICE 'team_memberships_unique_member constraint issue: %', SQLERRM;
END $$;

-- RLS: Team owners can manage memberships for their team
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Owners manage team_memberships' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Owners manage team_memberships"
      ON public.team_memberships FOR ALL
      USING (auth.uid() = team_owner_id)
      WITH CHECK (auth.uid() = team_owner_id);
  END IF;
END $$;

-- RLS: Members can view their own membership records
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members can view own memberships' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Members can view own memberships"
      ON public.team_memberships FOR SELECT
      USING (auth.uid() = member_user_id);
  END IF;
END $$;

-- RLS: Members can insert their own membership (when accepting an invite)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members can insert own membership' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Members can insert own membership"
      ON public.team_memberships FOR INSERT
      WITH CHECK (auth.uid() = member_user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_team_memberships_owner   ON public.team_memberships(team_owner_id);
CREATE INDEX IF NOT EXISTS idx_team_memberships_member  ON public.team_memberships(member_user_id);
CREATE INDEX IF NOT EXISTS idx_team_memberships_status  ON public.team_memberships(status);


-- ============================================================
-- 6. parts_usage_log — CREATE MISSING TABLE
-- ============================================================
-- Used by: teamMembership.ts (fetchPartsUsageLog, insertPartsUsage, deletePartsUsage)
-- Tracks parts deducted from inventory when work orders complete or maintenance is performed.
CREATE TABLE IF NOT EXISTS public.parts_usage_log (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  part_id          TEXT NOT NULL,
  part_number      TEXT NOT NULL,
  part_description TEXT,
  quantity_used    INTEGER DEFAULT 1,
  unit_cost        NUMERIC DEFAULT 0,
  total_cost       NUMERIC DEFAULT 0,
  usage_date       TEXT NOT NULL,
  usage_type       TEXT DEFAULT 'work_order',     -- 'work_order' or 'maintenance'
  related_id       TEXT,                          -- work_order.id or maintenance_item.id
  related_title    TEXT,                          -- work order title or maintenance component name
  notes            TEXT,
  recorded_by      TEXT,                          -- name of person who recorded the usage
  previous_on_hand INTEGER DEFAULT 0,
  new_on_hand      INTEGER DEFAULT 0,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.parts_usage_log ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own parts_usage_log' AND tablename = 'parts_usage_log') THEN
    CREATE POLICY "Users manage own parts_usage_log"
      ON public.parts_usage_log FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_parts_usage_user_id     ON public.parts_usage_log(user_id);
CREATE INDEX IF NOT EXISTS idx_parts_usage_part_id     ON public.parts_usage_log(part_id);
CREATE INDEX IF NOT EXISTS idx_parts_usage_date        ON public.parts_usage_log(usage_date DESC);
CREATE INDEX IF NOT EXISTS idx_parts_usage_type        ON public.parts_usage_log(usage_type);
CREATE INDEX IF NOT EXISTS idx_parts_usage_related     ON public.parts_usage_log(related_id);


-- ============================================================
-- 7. user_settings — ENSURE TABLE EXISTS
-- ============================================================
-- Already in supabase_schema.sql but may not have been run.
CREATE TABLE IF NOT EXISTS public.user_settings (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  feature     TEXT NOT NULL,
  settings    JSONB DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, feature)
);

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own user_settings' AND tablename = 'user_settings') THEN
    CREATE POLICY "Users manage own user_settings"
      ON public.user_settings FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_settings_user_id ON public.user_settings(user_id);


-- ============================================================
-- 8. team_notes — ENSURE TABLE EXISTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_notes (
  id          TEXT PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  content     TEXT,
  category    TEXT DEFAULT 'General',
  created_by  TEXT,
  is_pinned   BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.team_notes ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own team_notes' AND tablename = 'team_notes') THEN
    CREATE POLICY "Users manage own team_notes"
      ON public.team_notes FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_team_notes_user_id ON public.team_notes(user_id);


-- ============================================================
-- 9. labor_entries — ENSURE TABLE EXISTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.labor_entries (
  id                TEXT PRIMARY KEY,
  user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  team_member_id    TEXT,
  team_member_name  TEXT NOT NULL,
  date              TEXT NOT NULL,
  hours             NUMERIC DEFAULT 0,
  hourly_rate       NUMERIC DEFAULT 125,
  daily_rate        NUMERIC,
  rate_type         TEXT DEFAULT 'hourly',
  total_cost        NUMERIC DEFAULT 0,
  description       TEXT,
  category          TEXT DEFAULT 'Shop Work',
  notes             TEXT,
  event_id          TEXT,
  event_name        TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.labor_entries ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own labor_entries' AND tablename = 'labor_entries') THEN
    CREATE POLICY "Users manage own labor_entries"
      ON public.labor_entries FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_labor_entries_user_id ON public.labor_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_labor_entries_date    ON public.labor_entries(date DESC);


-- ============================================================
-- 10. todo_items — ENSURE TABLE EXISTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.todo_items (
  id               TEXT PRIMARY KEY,
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title            TEXT NOT NULL,
  description      TEXT,
  priority         TEXT DEFAULT 'Medium',
  status           TEXT DEFAULT 'Pending',
  category         TEXT DEFAULT 'General',
  assigned_to      TEXT,
  created_by       TEXT,
  created_by_role  TEXT,
  due_date         TEXT,
  completed_date   TEXT,
  completed_by     TEXT,
  tags             JSONB DEFAULT '[]'::jsonb,
  is_archived      BOOLEAN DEFAULT FALSE,
  archived_at      TEXT,
  archived_by      TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.todo_items ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own todo_items' AND tablename = 'todo_items') THEN
    CREATE POLICY "Users manage own todo_items"
      ON public.todo_items FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_todo_items_user_id ON public.todo_items(user_id);


-- ============================================================
-- 11. checklists — ENSURE checked_by / checked_at COLUMNS EXIST
-- ============================================================
ALTER TABLE public.checklists
  ADD COLUMN IF NOT EXISTS checked_by TEXT;

ALTER TABLE public.checklists
  ADD COLUMN IF NOT EXISTS checked_at TEXT;


-- ============================================================
-- 12. saved_tracks — ENSURE DEFAULT on user_id
-- ============================================================
-- The InitialSetup.tsx saveTrack function doesn't include user_id
-- in the payload, so we need a DEFAULT.
DO $$ BEGIN
  BEGIN
    ALTER TABLE public.saved_tracks ALTER COLUMN user_id SET DEFAULT auth.uid();
  EXCEPTION WHEN others THEN
    RAISE NOTICE 'saved_tracks user_id default already set or error: %', SQLERRM;
  END;
END $$;


-- ============================================================
-- 13. ALL REMAINING TABLES — ENSURE user_id DEFAULT auth.uid()
-- ============================================================
-- Many tables are missing DEFAULT auth.uid() on user_id, causing
-- RLS violations when the frontend doesn't explicitly set user_id.

DO $$ BEGIN
  BEGIN ALTER TABLE public.engines ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.superchargers ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.cylinder_heads ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.pass_logs ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.maintenance_items ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.sfi_certifications ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.work_orders ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.engine_swap_logs ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.checklists ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.parts_inventory ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.track_weather_history ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.race_events ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.team_members ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.media_gallery ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.transmissions ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.setup_vendors ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.team_notes ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.labor_entries ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
  BEGIN ALTER TABLE public.todo_items ALTER COLUMN user_id SET DEFAULT auth.uid(); EXCEPTION WHEN others THEN NULL; END;
END $$;


-- ============================================================
-- 14. ALL INDEXES — ENSURE THEY EXIST
-- ============================================================
-- Core table indexes
CREATE INDEX IF NOT EXISTS idx_pass_logs_user_id        ON public.pass_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_pass_logs_date           ON public.pass_logs(date DESC);
CREATE INDEX IF NOT EXISTS idx_engines_user_id          ON public.engines(user_id);
CREATE INDEX IF NOT EXISTS idx_superchargers_user_id    ON public.superchargers(user_id);
CREATE INDEX IF NOT EXISTS idx_cylinder_heads_user_id   ON public.cylinder_heads(user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_user_id      ON public.maintenance_items(user_id);
CREATE INDEX IF NOT EXISTS idx_sfi_certs_user_id        ON public.sfi_certifications(user_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_user_id      ON public.work_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_checklists_user_id       ON public.checklists(user_id);
CREATE INDEX IF NOT EXISTS idx_checklists_type          ON public.checklists(checklist_type);
CREATE INDEX IF NOT EXISTS idx_parts_inv_user_id        ON public.parts_inventory(user_id);
CREATE INDEX IF NOT EXISTS idx_parts_inv_category       ON public.parts_inventory(category);
CREATE INDEX IF NOT EXISTS idx_race_events_user_id      ON public.race_events(user_id);
CREATE INDEX IF NOT EXISTS idx_race_events_date         ON public.race_events(start_date DESC);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id     ON public.team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_media_gallery_user_id    ON public.media_gallery(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_tracks_user_id     ON public.saved_tracks(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id       ON public.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp     ON public.audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chassis_setups_user_id   ON public.chassis_setups(user_id);
CREATE INDEX IF NOT EXISTS idx_transmissions_user_id    ON public.transmissions(user_id);
CREATE INDEX IF NOT EXISTS idx_setup_vendors_user_id    ON public.setup_vendors(user_id);
CREATE INDEX IF NOT EXISTS idx_vendor_invoices_user_id  ON public.vendor_invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_swap_logs_user_id        ON public.engine_swap_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_weather_hist_user_id     ON public.track_weather_history(user_id);
CREATE INDEX IF NOT EXISTS idx_todo_items_user_id       ON public.todo_items(user_id);
CREATE INDEX IF NOT EXISTS idx_user_settings_user_id    ON public.user_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_team_notes_user_id       ON public.team_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_labor_entries_user_id    ON public.labor_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_labor_entries_date       ON public.labor_entries(date DESC);


-- ============================================================
-- 15. RPC FUNCTION — increment_track_visit
-- ============================================================
CREATE OR REPLACE FUNCTION public.increment_track_visit(track_id TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.saved_tracks
  SET visit_count = COALESCE(visit_count, 0) + 1,
      last_visited = TO_CHAR(NOW(), 'YYYY-MM-DD'),
      updated_at = NOW()
  WHERE id = track_id
    AND user_id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================================
-- 16. TRIGGER — Auto-create profile on signup
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (id, user_id, team_name, contact_email, created_at, updated_at)
  VALUES (
    NEW.id,
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'team_name', 'My Race Team'),
    NEW.email,
    NOW(),
    NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    user_id = EXCLUDED.user_id
  WHERE public.user_profiles.user_id IS NULL;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 17. HELPER FUNCTIONS FOR TEAM MEMBER DATA ACCESS
-- ============================================================
-- These functions allow team members to read team owner's data
-- when they have the appropriate permissions.

CREATE OR REPLACE FUNCTION public.is_team_member_of(owner_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.team_memberships
    WHERE team_owner_id = owner_id
      AND member_user_id = auth.uid()
      AND status = 'active'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION public.has_team_edit_permission(owner_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.team_memberships
    WHERE team_owner_id = owner_id
      AND member_user_id = auth.uid()
      AND status = 'active'
      AND permissions ? 'edit'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;


-- ============================================================
-- DONE! Migration complete.
-- ============================================================
-- Summary of changes:
--   1. user_profiles: Added user_id column (mirrors id), backfilled, indexed
--   2. engines: Added displacement column
--   3. setup_vendors: Added 6 columns (discount_percent, lead_time_days,
--      minimum_order, shipping_method, is_active, created_date)
--   4. team_invites: Created new table with RLS
--   5. team_memberships: Created new table with RLS
--   6. parts_usage_log: Created new table with RLS
--   7. user_settings: Ensured exists
--   8. team_notes: Ensured exists
--   9. labor_entries: Ensured exists
--  10. todo_items: Ensured exists
--  11. checklists: Ensured checked_by/checked_at columns exist
--  12. saved_tracks: Added DEFAULT auth.uid() on user_id
--  13. ALL tables: Added DEFAULT auth.uid() on user_id columns
--  14. ALL indexes: Ensured all performance indexes exist
--  15. RPC: increment_track_visit function
--  16. Trigger: Updated handle_new_user to also set user_id
--  17. Helper functions: is_team_member_of, has_team_edit_permission
-- ============================================================
