-- ════════════════════════════════════════════════════════════════════════════
-- MASTER DATABASE SYNC SCRIPT  —  ProMod Race Manager
-- ════════════════════════════════════════════════════════════════════════════
--
-- WHAT THIS IS
--   ONE complete, idempotent SQL script that creates EVERY table and column the
--   app code references via supabase.from('...'). Safe to run as many times as
--   you like — every statement uses CREATE TABLE IF NOT EXISTS, ALTER TABLE ADD
--   COLUMN IF NOT EXISTS, or CREATE INDEX IF NOT EXISTS. Existing data is never
--   touched.
--
-- HOW TO RUN
--   Paste the whole file into the Supabase SQL Editor and press "Run" ONCE.
--   At the bottom it enables Row Level Security + an owner policy on every table
--   and refreshes the PostgREST schema cache.
--
-- COVERAGE
--   This was generated by scanning the entire codebase for every
--   supabase.from('<table>') reference and every column the app reads/writes.
--   It resolves the reported PGRST205 ("table not in schema cache") and 400
--   ("column does not exist") errors — including:
--     • maintenance_items.service_log / last_service_time / threshold
--     • tire_sets / tire_tread_depth / tire_pressure_history / tire_change_log
--     • maintenance_categories / maintenance_alert_settings /
--       maintenance_category_overrides
--     • team_activity_feed / pass_history / offline_queue / track_records
-- ════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- CORE COMPONENTS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.engines (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, serial_number TEXT, builder TEXT,
  install_date TEXT, total_passes INTEGER, passes_since_rebuild INTEGER, status TEXT,
  currently_installed BOOLEAN, notes TEXT, components JSONB DEFAULT '{}'::jsonb,
  displacement TEXT, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.superchargers (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, serial_number TEXT, model TEXT,
  install_date TEXT, total_passes INTEGER, passes_since_service INTEGER, status TEXT,
  currently_installed BOOLEAN, notes TEXT, power_adder_type TEXT, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.superchargers ADD COLUMN IF NOT EXISTS power_adder_type TEXT;

CREATE TABLE IF NOT EXISTS public.cylinder_heads (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, serial_number TEXT, builder TEXT,
  install_date TEXT, total_passes INTEGER, passes_since_refresh INTEGER, status TEXT,
  position TEXT, engine_id TEXT, notes TEXT, components JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transmissions (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, serial_number TEXT, type TEXT,
  model TEXT, builder TEXT, gear_count INTEGER, install_date TEXT, total_passes INTEGER,
  status TEXT, currently_installed BOOLEAN, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.drivetrain_components (
  id TEXT PRIMARY KEY, user_id UUID, category TEXT, name TEXT, make TEXT, model TEXT,
  serial_number TEXT, builder TEXT, install_date TEXT, date_removed TEXT,
  total_passes INTEGER, passes_since_service INTEGER, hours NUMERIC, status TEXT,
  currently_installed BOOLEAN, notes TEXT, components JSONB DEFAULT '{}'::jsonb, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.component_parts (
  id TEXT PRIMARY KEY, user_id UUID, component_id TEXT, component_type TEXT,
  part_name TEXT, passes_on_part INTEGER DEFAULT 0, date_replaced TEXT, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.component_parts ADD COLUMN IF NOT EXISTS date_replaced TEXT;
ALTER TABLE public.component_parts ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS public.component_extra_fields (
  id TEXT PRIMARY KEY, user_id UUID, component_id TEXT, component_type TEXT,
  fields JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.engine_swap_logs (
  id TEXT PRIMARY KEY, user_id UUID, date TEXT, time TEXT, previous_engine_id TEXT,
  new_engine_id TEXT, reason TEXT, performed_by TEXT, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.drivetrain_swap_logs (
  id TEXT PRIMARY KEY, user_id UUID, date TEXT, time TEXT, component_type TEXT,
  previous_component_id TEXT, new_component_id TEXT, previous_component_name TEXT,
  new_component_name TEXT, reason TEXT, performed_by TEXT, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.race_cars (
  id TEXT PRIMARY KEY, user_id UUID, car_number TEXT, nickname TEXT, name TEXT,
  class TEXT, class_type TEXT, year INTEGER, make TEXT, model TEXT, color TEXT,
  vin TEXT, weight NUMERIC, photo_url TEXT, is_active BOOLEAN, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- MAINTENANCE  (includes the previously-missing columns)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.maintenance_items (
  id TEXT PRIMARY KEY, user_id UUID, component TEXT, category TEXT,
  pass_interval INTEGER, current_passes INTEGER, last_service TEXT,
  last_service_time TEXT, next_service_passes INTEGER, status TEXT, priority TEXT,
  notes TEXT, estimated_cost NUMERIC, threshold INTEGER, service_log JSONB DEFAULT '[]'::jsonb,
  car_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS last_service_time TEXT;
ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS threshold INTEGER;
ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS service_log JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS car_id TEXT;

CREATE TABLE IF NOT EXISTS public.maintenance_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, name TEXT, color TEXT,
  sort_order INTEGER, created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.maintenance_categories ADD COLUMN IF NOT EXISTS sort_order INTEGER;

CREATE TABLE IF NOT EXISTS public.maintenance_category_overrides (
  user_id UUID PRIMARY KEY, data JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.maintenance_alert_settings (
  user_id UUID PRIMARY KEY, is_enabled BOOLEAN DEFAULT TRUE, notify_toast BOOLEAN DEFAULT TRUE,
  notify_bell BOOLEAN DEFAULT TRUE, thresholds_json JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- SFI
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sfi_certifications (
  id TEXT PRIMARY KEY, user_id UUID, item TEXT, sfi_spec TEXT, certification_date TEXT,
  expiration_date TEXT, vendor TEXT, serial_number TEXT, status TEXT,
  days_until_expiration INTEGER, notes TEXT, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sfi_alert_settings (
  user_id UUID PRIMARY KEY, is_enabled BOOLEAN DEFAULT TRUE, notify_toast BOOLEAN DEFAULT TRUE,
  notify_bell BOOLEAN DEFAULT TRUE, thresholds_json JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- PASS LOGS / HISTORY
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pass_logs (
  id TEXT PRIMARY KEY, user_id UUID, date TEXT, time TEXT, track TEXT, location TEXT,
  session_type TEXT, round TEXT, lane TEXT, result TEXT, reaction_time NUMERIC,
  sixty_foot NUMERIC, three_thirty NUMERIC, eighth NUMERIC, mph NUMERIC,
  quarter_mile_et NUMERIC, quarter_mile_mph NUMERIC, quarter_back_split NUMERIC,
  weather JSONB DEFAULT '{}'::jsonb, sae_correction NUMERIC, density_altitude NUMERIC,
  corrected_hp NUMERIC, engine_id TEXT, supercharger_id TEXT, tire_pressure_front NUMERIC,
  tire_pressure_rear_left NUMERIC, tire_pressure_rear_right NUMERIC,
  rear_left_liner_psi NUMERIC, rear_right_liner_psi NUMERIC, wheelie_bar_setting NUMERIC,
  launch_rpm NUMERIC, boost_setting NUMERIC, notes TEXT, crew_chief TEXT,
  aborted BOOLEAN DEFAULT FALSE, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS quarter_mile_et NUMERIC;
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS quarter_mile_mph NUMERIC;
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS quarter_back_split NUMERIC;
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS rear_left_liner_psi NUMERIC;
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS rear_right_liner_psi NUMERIC;
ALTER TABLE public.pass_logs ADD COLUMN IF NOT EXISTS car_id TEXT;

CREATE TABLE IF NOT EXISTS public.pass_history (
  id TEXT PRIMARY KEY, user_id UUID, pass_count INTEGER DEFAULT 1,
  components_updated INTEGER DEFAULT 0, flagged_count INTEGER DEFAULT 0,
  flagged_details JSONB DEFAULT '[]'::jsonb, engines_updated JSONB DEFAULT '[]'::jsonb,
  heads_updated JSONB DEFAULT '[]'::jsonb, power_adders_updated JSONB DEFAULT '[]'::jsonb,
  drivetrain_updated JSONB DEFAULT '[]'::jsonb, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CHECKLISTS / TODO / TEAM NOTES
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.checklists (
  id TEXT PRIMARY KEY, user_id UUID, checklist_type TEXT, task TEXT, category TEXT,
  completed BOOLEAN DEFAULT FALSE, notes TEXT, critical BOOLEAN DEFAULT FALSE,
  checked_by TEXT, checked_at TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.todo_items (
  id TEXT PRIMARY KEY, user_id UUID, title TEXT, description TEXT, priority TEXT,
  status TEXT, category TEXT, assigned_to TEXT, created_by TEXT, created_by_role TEXT,
  due_date TEXT, completed_date TEXT, completed_by TEXT, tags JSONB DEFAULT '[]'::jsonb,
  is_archived BOOLEAN DEFAULT FALSE, archived_at TEXT, archived_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.todo_items ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE;
ALTER TABLE public.todo_items ADD COLUMN IF NOT EXISTS archived_at TEXT;
ALTER TABLE public.todo_items ADD COLUMN IF NOT EXISTS archived_by TEXT;

CREATE TABLE IF NOT EXISTS public.team_notes (
  id TEXT PRIMARY KEY, user_id UUID, title TEXT, content TEXT, category TEXT,
  created_by TEXT, is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TRACKS / EVENTS / WEATHER / RECORDS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.saved_tracks (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, location TEXT, address TEXT, city TEXT,
  state TEXT, zip TEXT, elevation NUMERIC, track_length TEXT, surface_type TEXT, notes TEXT,
  is_favorite BOOLEAN DEFAULT FALSE, last_visited TEXT, visit_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.track_weather_history (
  id TEXT PRIMARY KEY, user_id UUID, track_id TEXT, track_name TEXT, location TEXT,
  elevation NUMERIC, visits JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.track_records (
  id TEXT PRIMARY KEY, user_id UUID, track_id TEXT NOT NULL, track_name TEXT NOT NULL,
  category TEXT NOT NULL, value NUMERIC NOT NULL, pass_id TEXT, pass_date TEXT,
  driver_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.race_events (
  id TEXT PRIMARY KEY, user_id UUID, title TEXT, event_type TEXT, track_name TEXT,
  track_location TEXT, track_address TEXT, track_zip TEXT, start_date TEXT, end_date TEXT,
  start_time TEXT, end_time TEXT, status TEXT, sanctioning_body TEXT, entry_fee NUMERIC,
  purse NUMERIC, notes TEXT, result TEXT, best_et NUMERIC, best_mph NUMERIC, rounds_won INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.race_events ADD COLUMN IF NOT EXISTS track_address TEXT;
ALTER TABLE public.race_events ADD COLUMN IF NOT EXISTS track_zip TEXT;

-- ─────────────────────────────────────────────────────────────────────────────
-- TIRES  (previously-missing tables)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.tire_sets (
  id TEXT PRIMARY KEY, user_id UUID, brand TEXT, model TEXT, size TEXT, compound TEXT,
  position TEXT, status TEXT, install_date TEXT, total_passes INTEGER DEFAULT 0, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tire_tread_depth (
  id TEXT PRIMARY KEY, user_id UUID, tire_set_id TEXT, date TEXT, depth NUMERIC,
  pass_count INTEGER, location TEXT, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tire_pressure_history (
  id TEXT PRIMARY KEY, user_id UUID, tire_set_id TEXT, date TEXT, pass_number INTEGER,
  pressure_before NUMERIC, pressure_after NUMERIC, hot_pressure NUMERIC, track_temp NUMERIC, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tire_change_log (
  id TEXT PRIMARY KEY, user_id UUID, tire_set_id TEXT, tire_set_name TEXT, date TEXT,
  pass_count INTEGER, action TEXT, reason TEXT, performed_by TEXT, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- EXPENSES / INVOICES / VENDORS / PARTS USAGE
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.parts_inventory (
  id TEXT PRIMARY KEY, user_id UUID, part_number TEXT, description TEXT, name TEXT,
  category TEXT, subcategory TEXT, on_hand INTEGER DEFAULT 0, min_quantity INTEGER DEFAULT 1,
  max_quantity INTEGER DEFAULT 5, vendor TEXT, vendor_part_number TEXT, unit_cost NUMERIC,
  total_value NUMERIC, last_ordered TEXT, last_used TEXT, location TEXT, notes TEXT,
  status TEXT, reorder_status TEXT, related_drivetrain_component_id TEXT, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parts_usage_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, part_id TEXT, part_number TEXT,
  part_description TEXT, quantity_used INTEGER, unit_cost NUMERIC, total_cost NUMERIC,
  usage_date TEXT, usage_type TEXT, related_id TEXT, related_title TEXT, notes TEXT,
  recorded_by TEXT, previous_on_hand INTEGER, new_on_hand INTEGER, created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.setup_vendors (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, code TEXT, contact_name TEXT, email TEXT,
  phone TEXT, address TEXT, city TEXT, state TEXT, zip TEXT, website TEXT, category TEXT,
  payment_terms TEXT, notes TEXT, rating INTEGER, discount_percent NUMERIC, lead_time_days INTEGER,
  minimum_order NUMERIC, shipping_method TEXT, is_active BOOLEAN DEFAULT TRUE, created_date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.vendor_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, vendor_id TEXT, vendor_name TEXT,
  invoice_number TEXT, invoice_date TEXT, due_date TEXT, amount NUMERIC, tax NUMERIC, total NUMERIC,
  status TEXT, po_number TEXT, file_url TEXT, file_name TEXT, file_type TEXT, file_size BIGINT,
  notes TEXT, category TEXT, payment_method TEXT, payment_date TEXT, paid_date TEXT, receipt_url TEXT,
  linked_event_id TEXT, linked_event_name TEXT, car_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.invoice_line_items (
  id TEXT PRIMARY KEY, user_id UUID, invoice_id TEXT, description TEXT, part_number TEXT,
  category TEXT, quantity NUMERIC, unit_cost NUMERIC, unit_price NUMERIC, total NUMERIC,
  vendor_part_number TEXT, notes TEXT, auto_created_inventory_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cost_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, invoice_id TEXT, vendor_name TEXT,
  amount NUMERIC, category TEXT, date TEXT, description TEXT, source TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.misc_expenses (
  id TEXT PRIMARY KEY, user_id UUID, category TEXT, custom_description TEXT, amount NUMERIC,
  expense_date TEXT, paid_by TEXT, payment_method TEXT, receipt_url TEXT, receipt_file_name TEXT,
  receipt_file_type TEXT, receipt_file_size INTEGER, notes TEXT, race_event_id TEXT,
  linked_event_name TEXT, add_to_cost_report BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.borrowed_loaned_parts (
  id TEXT PRIMARY KEY, user_id UUID, transaction_type TEXT, part_name TEXT, part_number TEXT,
  description TEXT, quantity INTEGER, person_name TEXT, contact TEXT, date_transaction TEXT,
  expected_return_date TEXT, actual_return_date TEXT, condition_out TEXT, condition_returned TEXT,
  notes TEXT, status TEXT, linked_inventory_id TEXT, inventory_adjusted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.borrowed_loaned_parts ADD COLUMN IF NOT EXISTS inventory_adjusted BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.fuel_log_entries (
  id TEXT PRIMARY KEY, user_id UUID, team_id UUID, car_id TEXT, date TEXT, fuel_type TEXT,
  quantity_gallons NUMERIC, price_per_gallon NUMERIC, total_cost NUMERIC, vendor TEXT, notes TEXT,
  race_event_id TEXT, linked_event_name TEXT, gallons_used NUMERIC, passes_at_event INTEGER,
  receipt_number TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.labor_entries (
  id TEXT PRIMARY KEY, user_id UUID, team_member_id TEXT, team_member_name TEXT, date TEXT,
  hours NUMERIC, hourly_rate NUMERIC, daily_rate NUMERIC, rate_type TEXT, total_cost NUMERIC,
  description TEXT, category TEXT, notes TEXT, event_id TEXT, event_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CHASSIS / SETUPS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.chassis_setups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, name TEXT, description TEXT,
  race_event TEXT, race_date TEXT, track_name TEXT, track_conditions TEXT, weather_conditions TEXT,
  upper_bar_chassis_x NUMERIC, upper_bar_chassis_y NUMERIC, upper_bar_rear_x NUMERIC, upper_bar_rear_y NUMERIC,
  lower_bar_chassis_x NUMERIC, lower_bar_chassis_y NUMERIC, lower_bar_rear_x NUMERIC, lower_bar_rear_y NUMERIC,
  rear_end_center_height NUMERIC, instant_center_length NUMERIC, instant_center_height NUMERIC,
  anti_squat_percentage NUMERIC, corner_weights JSONB, ballast_items JSONB, total_weight NUMERIC,
  cross_weight_percentage NUMERIC, shock_settings JSONB, ride_heights JSONB, spring_data JSONB,
  cg_data JSONB, pinion_data JSONB, performance_notes TEXT, sixty_foot_time NUMERIC,
  eighth_mile_et NUMERIC, eighth_mile_mph NUMERIC, quarter_mile_et NUMERIC, quarter_mile_mph NUMERIC,
  is_favorite BOOLEAN, tags JSONB, created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chassis_setup_user_presets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, name TEXT, description TEXT,
  category TEXT, settings JSONB, recommended_pinion_angle NUMERIC, target_anti_squat_min NUMERIC,
  target_anti_squat_max NUMERIC, characteristics JSONB, notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- TEAM / USER / SETTINGS / AUDIT / FEEDBACK
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.team_members (
  id TEXT PRIMARY KEY, user_id UUID, name TEXT, email TEXT, phone TEXT, role TEXT,
  permissions JSONB DEFAULT '[]'::jsonb, specialties JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT TRUE, joined_date TEXT, emergency_contact_name TEXT,
  emergency_contact_phone TEXT, notes TEXT, avatar_url TEXT, hourly_rate NUMERIC, daily_rate NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.team_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), team_owner_id UUID, email TEXT, role TEXT,
  permissions JSONB DEFAULT '[]'::jsonb, token TEXT, status TEXT, invited_by_name TEXT,
  team_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), expires_at TIMESTAMPTZ, accepted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.team_memberships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), team_owner_id UUID, member_user_id UUID,
  team_member_id TEXT, role TEXT, permissions JSONB DEFAULT '[]'::jsonb, status TEXT,
  joined_at TIMESTAMPTZ DEFAULT NOW(), invite_id UUID
);

CREATE TABLE IF NOT EXISTS public.team_activity_feed (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, action_type TEXT, description TEXT,
  member_name TEXT, metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.team_activity_feed ADD COLUMN IF NOT EXISTS member_name TEXT;
ALTER TABLE public.team_activity_feed ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID PRIMARY KEY, user_id UUID, team_name TEXT, driver_name TEXT, driver_license_number TEXT,
  driver_license_class TEXT, car_name TEXT, car_number TEXT, car_class TEXT, car_make TEXT,
  car_model TEXT, car_year INTEGER, car_weight NUMERIC, engine_type TEXT, fuel_type TEXT,
  home_track TEXT, team_logo_url TEXT, contact_email TEXT, contact_phone TEXT, notes TEXT,
  weather_source TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS weather_source TEXT;

CREATE TABLE IF NOT EXISTS public.user_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, feature TEXT, settings JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.media_gallery (
  id TEXT PRIMARY KEY, user_id UUID, title TEXT, description TEXT, media_type TEXT, url TEXT,
  thumbnail_url TEXT, category TEXT, tags JSONB DEFAULT '[]'::jsonb, event_name TEXT, event_date TEXT,
  uploaded_by TEXT, file_size BIGINT, duration NUMERIC, width INTEGER, height INTEGER,
  is_featured BOOLEAN DEFAULT FALSE, is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), timestamp TIMESTAMPTZ DEFAULT NOW(), user_id TEXT,
  user_name TEXT, user_role TEXT, action_type TEXT, category TEXT, entity_type TEXT, entity_id TEXT,
  entity_name TEXT, description TEXT, before_value JSONB, after_value JSONB, metadata JSONB
);

CREATE TABLE IF NOT EXISTS public.beta_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, category TEXT, title TEXT,
  description TEXT, status TEXT DEFAULT 'new', priority TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.offline_queue (
  id TEXT PRIMARY KEY, user_id UUID, operation_type TEXT, table_name TEXT, payload JSONB,
  status TEXT DEFAULT 'pending', retry_count INTEGER DEFAULT 0, max_retries INTEGER DEFAULT 5,
  label TEXT, created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY + OWNER POLICIES (idempotent, applied to every table)
-- ════════════════════════════════════════════════════════════════════════════
-- Each owner-scoped table gets a permissive policy:
--   user_id = auth.uid()  OR  user_id IS NULL   (legacy rows stay accessible)
-- A few tables use a different owner column (team_owner_id) and are handled too.

DO $$
DECLARE
  t TEXT;
  owner_col TEXT;
  owner_tables TEXT[] := ARRAY[
    'engines','superchargers','cylinder_heads','transmissions','drivetrain_components',
    'component_parts','component_extra_fields','engine_swap_logs','drivetrain_swap_logs',
    'race_cars','maintenance_items','maintenance_categories','maintenance_category_overrides',
    'maintenance_alert_settings','sfi_certifications','sfi_alert_settings','pass_logs',
    'pass_history','checklists','todo_items','team_notes','saved_tracks','track_weather_history',
    'track_records','race_events','tire_sets','tire_tread_depth','tire_pressure_history',
    'tire_change_log','parts_inventory','parts_usage_log','setup_vendors','vendor_invoices',
    'invoice_line_items','cost_reports','misc_expenses','borrowed_loaned_parts','fuel_log_entries',
    'labor_entries','chassis_setups','chassis_setup_user_presets','team_members','team_activity_feed',
    'user_profiles','user_settings','media_gallery','audit_logs','beta_feedback','offline_queue'
  ];
BEGIN
  -- user_id-scoped tables
  FOREACH t IN ARRAY owner_tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', t || '_owner', t);
    -- audit_logs.user_id is TEXT; everything else is UUID. The cast keeps the
    -- policy valid for both shapes.
    IF t = 'audit_logs' THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR ALL USING (user_id = auth.uid()::text OR user_id IS NULL) WITH CHECK (user_id = auth.uid()::text OR user_id IS NULL);',
        t || '_owner', t);
    ELSE
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR ALL USING (user_id = auth.uid() OR user_id IS NULL) WITH CHECK (user_id = auth.uid() OR user_id IS NULL);',
        t || '_owner', t);
    END IF;
  END LOOP;

  -- team_owner_id-scoped tables (invites / memberships)
  FOR t, owner_col IN
    SELECT 'team_invites','team_owner_id'
    UNION ALL SELECT 'team_memberships','team_owner_id'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', t || '_owner', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL USING (%I = auth.uid() OR %I IS NULL) WITH CHECK (%I = auth.uid() OR %I IS NULL);',
      t || '_owner', t, owner_col, owner_col, owner_col, owner_col);
  END LOOP;
END $$;

-- ════════════════════════════════════════════════════════════════════════════
-- REFRESH POSTGREST SCHEMA CACHE
-- ════════════════════════════════════════════════════════════════════════════
NOTIFY pgrst, 'reload schema';
