-- ============================================================
-- PRO MOD LOGBOOK — COMPLETE MASTER DATABASE SCHEMA
-- ============================================================
-- Run this ONE script in the Supabase SQL Editor to create
-- EVERY table, column, RLS policy, index, function, trigger,
-- and storage bucket the app needs.
--
-- This is idempotent — safe to run multiple times.
-- Every CREATE uses IF NOT EXISTS, every policy is wrapped
-- in a DO block that checks before creating.
--
-- Generated by auditing every .from('table_name') call,
-- every database.ts converter, every validator schema, and
-- every component's direct Supabase usage.
--
-- Tables (38 total):
--   1.  user_profiles          14. team_members
--   2.  engines                15. media_gallery
--   3.  superchargers          16. saved_tracks
--   4.  cylinder_heads         17. audit_logs
--   5.  pass_logs              18. beta_feedback
--   6.  maintenance_items      19. chassis_setups
--   7.  sfi_certifications     20. transmissions
--   8.  work_orders            21. setup_vendors
--   9.  engine_swap_logs       22. vendor_invoices
--  10.  checklists             23. invoice_line_items
--  11.  parts_inventory        24. cost_reports
--  12.  track_weather_history  25. todo_items
--  13.  race_events            26. user_settings
--  27.  team_notes             33. team_invites
--  28.  labor_entries          34. team_memberships
--  29.  race_cars              35. parts_usage_log
--  30.  drivetrain_components  36. misc_expenses
--  31.  drivetrain_swap_logs   37. borrowed_loaned_parts
--  32.  fuel_log_entries       38. chassis_setup_user_presets
--
-- Plus: RPC functions, triggers, storage bucket, indexes
-- ============================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. USER PROFILES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  user_id       UUID,
  team_name     TEXT NOT NULL DEFAULT 'My Race Team',
  driver_name   TEXT,
  driver_license_number TEXT,
  driver_license_class  TEXT,
  car_name      TEXT,
  car_number    TEXT,
  car_class     TEXT DEFAULT 'Pro Mod',
  car_make      TEXT,
  car_model     TEXT,
  car_year      INTEGER,
  car_weight    NUMERIC,
  engine_type   TEXT DEFAULT 'Supercharged Hemi',
  fuel_type     TEXT DEFAULT 'Methanol',
  home_track    TEXT,
  team_logo_url TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  notes         TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Backfill user_id from id for any existing rows
UPDATE public.user_profiles SET user_id = id WHERE user_id IS NULL;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can view own profile" ON public.user_profiles FOR SELECT USING (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can insert own profile" ON public.user_profiles FOR INSERT WITH CHECK (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can update own profile" ON public.user_profiles FOR UPDATE USING (auth.uid() = id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles(user_id);

-- ============================================================
-- 2. ENGINES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.engines (
  id                   TEXT PRIMARY KEY,
  user_id              UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                 TEXT NOT NULL,
  serial_number        TEXT,
  builder              TEXT,
  displacement         TEXT,
  install_date         TEXT,
  total_passes         INTEGER DEFAULT 0,
  passes_since_rebuild INTEGER DEFAULT 0,
  status               TEXT DEFAULT 'Ready',
  currently_installed  BOOLEAN DEFAULT FALSE,
  notes                TEXT,
  components           JSONB DEFAULT '{}'::jsonb,
  car_id               TEXT,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.engines ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own engines' AND tablename = 'engines') THEN
    CREATE POLICY "Users manage own engines" ON public.engines FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 3. SUPERCHARGERS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.superchargers (
  id                    TEXT PRIMARY KEY,
  user_id               UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                  TEXT NOT NULL,
  serial_number         TEXT,
  model                 TEXT,
  install_date          TEXT,
  total_passes          INTEGER DEFAULT 0,
  passes_since_service  INTEGER DEFAULT 0,
  status                TEXT DEFAULT 'Ready',
  currently_installed   BOOLEAN DEFAULT FALSE,
  notes                 TEXT,
  car_id                TEXT,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.superchargers ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own superchargers' AND tablename = 'superchargers') THEN
    CREATE POLICY "Users manage own superchargers" ON public.superchargers FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 4. CYLINDER HEADS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cylinder_heads (
  id                    TEXT PRIMARY KEY,
  user_id               UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                  TEXT NOT NULL,
  serial_number         TEXT,
  builder               TEXT,
  install_date          TEXT,
  total_passes          INTEGER DEFAULT 0,
  passes_since_refresh  INTEGER DEFAULT 0,
  status                TEXT DEFAULT 'Ready',
  position              TEXT DEFAULT 'Spare',
  engine_id             TEXT,
  notes                 TEXT,
  components            JSONB DEFAULT '{}'::jsonb,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cylinder_heads ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own cylinder_heads' AND tablename = 'cylinder_heads') THEN
    CREATE POLICY "Users manage own cylinder_heads" ON public.cylinder_heads FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 5. PASS LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.pass_logs (
  id                      TEXT PRIMARY KEY,
  user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date                    TEXT NOT NULL,
  time                    TEXT,
  track                   TEXT NOT NULL,
  location                TEXT,
  session_type            TEXT NOT NULL,
  round                   TEXT,
  lane                    TEXT,
  result                  TEXT,
  reaction_time           NUMERIC,
  sixty_foot              NUMERIC,
  three_thirty            NUMERIC,
  eighth                  NUMERIC,
  mph                     NUMERIC,
  weather                 JSONB DEFAULT '{}'::jsonb,
  sae_correction          NUMERIC DEFAULT 1,
  density_altitude        NUMERIC DEFAULT 0,
  corrected_hp            NUMERIC DEFAULT 0,
  engine_id               TEXT,
  supercharger_id         TEXT,
  tire_pressure_front     NUMERIC,
  tire_pressure_rear_left NUMERIC,
  tire_pressure_rear_right NUMERIC,
  wheelie_bar_setting     NUMERIC,
  launch_rpm              NUMERIC,
  boost_setting           NUMERIC,
  notes                   TEXT,
  crew_chief              TEXT,
  aborted                 BOOLEAN DEFAULT FALSE,
  car_id                  TEXT,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.pass_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own pass_logs' AND tablename = 'pass_logs') THEN
    CREATE POLICY "Users manage own pass_logs" ON public.pass_logs FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 6. MAINTENANCE ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.maintenance_items (
  id                  TEXT PRIMARY KEY,
  user_id             UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  component           TEXT NOT NULL,
  category            TEXT,
  pass_interval       INTEGER DEFAULT 0,
  current_passes      INTEGER DEFAULT 0,
  last_service        TEXT,
  next_service_passes INTEGER DEFAULT 0,
  status              TEXT DEFAULT 'Good',
  priority            TEXT DEFAULT 'Medium',
  notes               TEXT,
  estimated_cost      NUMERIC,
  car_id              TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.maintenance_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own maintenance_items' AND tablename = 'maintenance_items') THEN
    CREATE POLICY "Users manage own maintenance_items" ON public.maintenance_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 7. SFI CERTIFICATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sfi_certifications (
  id                     TEXT PRIMARY KEY,
  user_id                UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  item                   TEXT NOT NULL,
  sfi_spec               TEXT,
  certification_date     TEXT,
  expiration_date        TEXT,
  vendor                 TEXT,
  serial_number          TEXT,
  status                 TEXT DEFAULT 'Valid',
  days_until_expiration  INTEGER DEFAULT 0,
  notes                  TEXT,
  car_id                 TEXT,
  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sfi_certifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own sfi_certifications' AND tablename = 'sfi_certifications') THEN
    CREATE POLICY "Users manage own sfi_certifications" ON public.sfi_certifications FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 8. WORK ORDERS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.work_orders (
  id                 TEXT PRIMARY KEY,
  user_id            UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title              TEXT NOT NULL,
  description        TEXT,
  category           TEXT,
  priority           TEXT DEFAULT 'Medium',
  status             TEXT DEFAULT 'Open',
  created_date       TEXT,
  due_date           TEXT,
  completed_date     TEXT,
  assigned_to        TEXT,
  estimated_hours    NUMERIC,
  actual_hours       NUMERIC,
  parts              JSONB DEFAULT '[]'::jsonb,
  related_component  TEXT,
  notes              TEXT,
  car_id             TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own work_orders' AND tablename = 'work_orders') THEN
    CREATE POLICY "Users manage own work_orders" ON public.work_orders FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 9. ENGINE SWAP LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.engine_swap_logs (
  id                 TEXT PRIMARY KEY,
  user_id            UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date               TEXT NOT NULL,
  time               TEXT,
  previous_engine_id TEXT,
  new_engine_id      TEXT,
  reason             TEXT,
  performed_by       TEXT,
  notes              TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.engine_swap_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own engine_swap_logs' AND tablename = 'engine_swap_logs') THEN
    CREATE POLICY "Users manage own engine_swap_logs" ON public.engine_swap_logs FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 10. CHECKLISTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.checklists (
  id              TEXT PRIMARY KEY,
  user_id         UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  checklist_type  TEXT NOT NULL,
  task            TEXT NOT NULL,
  category        TEXT,
  completed       BOOLEAN DEFAULT FALSE,
  notes           TEXT,
  critical        BOOLEAN DEFAULT FALSE,
  checked_by      TEXT,
  checked_at      TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.checklists ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own checklists' AND tablename = 'checklists') THEN
    CREATE POLICY "Users manage own checklists" ON public.checklists FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 11. PARTS INVENTORY
-- ============================================================
CREATE TABLE IF NOT EXISTS public.parts_inventory (
  id                              TEXT PRIMARY KEY,
  user_id                         UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  part_number                     TEXT NOT NULL,
  description                     TEXT NOT NULL,
  name                            TEXT,
  category                        TEXT,
  subcategory                     TEXT,
  on_hand                         INTEGER DEFAULT 0,
  min_quantity                    INTEGER DEFAULT 1,
  max_quantity                    INTEGER DEFAULT 5,
  vendor                          TEXT,
  vendor_part_number              TEXT,
  unit_cost                       NUMERIC DEFAULT 0,
  total_value                     NUMERIC DEFAULT 0,
  last_ordered                    TEXT,
  last_used                       TEXT,
  location                        TEXT,
  notes                           TEXT,
  status                          TEXT DEFAULT 'In Stock',
  reorder_status                  TEXT DEFAULT 'OK',
  related_drivetrain_component_id TEXT,
  car_id                          TEXT,
  created_at                      TIMESTAMPTZ DEFAULT NOW(),
  updated_at                      TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.parts_inventory ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own parts_inventory' AND tablename = 'parts_inventory') THEN
    CREATE POLICY "Users manage own parts_inventory" ON public.parts_inventory FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 12. TRACK WEATHER HISTORY
-- ============================================================
CREATE TABLE IF NOT EXISTS public.track_weather_history (
  id          TEXT PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  track_id    TEXT NOT NULL,
  track_name  TEXT NOT NULL,
  location    TEXT,
  elevation   NUMERIC DEFAULT 0,
  visits      JSONB DEFAULT '[]'::jsonb,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.track_weather_history ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own track_weather_history' AND tablename = 'track_weather_history') THEN
    CREATE POLICY "Users manage own track_weather_history" ON public.track_weather_history FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 13. RACE EVENTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.race_events (
  id                TEXT PRIMARY KEY,
  user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title             TEXT NOT NULL,
  event_type        TEXT DEFAULT 'Race',
  track_name        TEXT,
  track_location    TEXT,
  track_address     TEXT,
  track_zip         TEXT,
  start_date        TEXT NOT NULL,
  end_date          TEXT,
  start_time        TEXT,
  end_time          TEXT,
  status            TEXT DEFAULT 'Scheduled',
  sanctioning_body  TEXT,
  entry_fee         NUMERIC,
  purse             NUMERIC,
  notes             TEXT,
  result            TEXT,
  best_et           NUMERIC,
  best_mph          NUMERIC,
  rounds_won        INTEGER,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.race_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own race_events' AND tablename = 'race_events') THEN
    CREATE POLICY "Users manage own race_events" ON public.race_events FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 14. TEAM MEMBERS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_members (
  id                      TEXT PRIMARY KEY,
  user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                    TEXT NOT NULL,
  email                   TEXT,
  phone                   TEXT,
  role                    TEXT DEFAULT 'Crew',
  permissions             JSONB DEFAULT '["view"]'::jsonb,
  specialties             JSONB DEFAULT '[]'::jsonb,
  is_active               BOOLEAN DEFAULT TRUE,
  joined_date             TEXT,
  emergency_contact_name  TEXT,
  emergency_contact_phone TEXT,
  notes                   TEXT,
  avatar_url              TEXT,
  hourly_rate             NUMERIC,
  daily_rate              NUMERIC,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own team_members' AND tablename = 'team_members') THEN
    CREATE POLICY "Users manage own team_members" ON public.team_members FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 15. MEDIA GALLERY
-- ============================================================
CREATE TABLE IF NOT EXISTS public.media_gallery (
  id             TEXT PRIMARY KEY,
  user_id        UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title          TEXT NOT NULL,
  description    TEXT,
  media_type     TEXT NOT NULL,
  url            TEXT NOT NULL,
  thumbnail_url  TEXT,
  category       TEXT DEFAULT 'General',
  tags           JSONB DEFAULT '[]'::jsonb,
  event_name     TEXT,
  event_date     TEXT,
  uploaded_by    TEXT,
  file_size      BIGINT,
  duration       NUMERIC,
  width          INTEGER,
  height         INTEGER,
  is_featured    BOOLEAN DEFAULT FALSE,
  is_public      BOOLEAN DEFAULT TRUE,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.media_gallery ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own media_gallery' AND tablename = 'media_gallery') THEN
    CREATE POLICY "Users manage own media_gallery" ON public.media_gallery FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 16. SAVED TRACKS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.saved_tracks (
  id            TEXT PRIMARY KEY,
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name          TEXT NOT NULL,
  location      TEXT NOT NULL,
  address       TEXT,
  city          TEXT,
  state         TEXT,
  zip           TEXT,
  elevation     NUMERIC DEFAULT 0,
  track_length  TEXT DEFAULT '1/8 mile',
  surface_type  TEXT DEFAULT 'Concrete',
  notes         TEXT,
  is_favorite   BOOLEAN DEFAULT FALSE,
  last_visited  TEXT,
  visit_count   INTEGER DEFAULT 0,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.saved_tracks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own saved_tracks' AND tablename = 'saved_tracks') THEN
    CREATE POLICY "Users manage own saved_tracks" ON public.saved_tracks FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 17. AUDIT LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  timestamp     TIMESTAMPTZ DEFAULT NOW(),
  user_id       TEXT NOT NULL,
  user_name     TEXT NOT NULL,
  user_role     TEXT NOT NULL,
  action_type   TEXT NOT NULL,
  category      TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT,
  entity_name   TEXT,
  description   TEXT NOT NULL,
  before_value  JSONB,
  after_value   JSONB,
  metadata      JSONB
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own audit_logs' AND tablename = 'audit_logs') THEN
    CREATE POLICY "Users manage own audit_logs" ON public.audit_logs FOR ALL USING (auth.uid()::text = user_id) WITH CHECK (auth.uid()::text = user_id);
  END IF;
END $$;

-- ============================================================
-- 18. BETA FEEDBACK
-- ============================================================
CREATE TABLE IF NOT EXISTS public.beta_feedback (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  category    TEXT NOT NULL,
  title       TEXT,
  description TEXT NOT NULL,
  status      TEXT DEFAULT 'new',
  priority    TEXT DEFAULT 'Medium',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);


ALTER TABLE public.beta_feedback ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert feedback' AND tablename = 'beta_feedback') THEN
    CREATE POLICY "Users can insert feedback" ON public.beta_feedback FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own feedback' AND tablename = 'beta_feedback') THEN
    CREATE POLICY "Users can view own feedback" ON public.beta_feedback FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 19. CHASSIS SETUPS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.chassis_setups (
  id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                  UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                     TEXT NOT NULL DEFAULT 'New Setup',
  description              TEXT,
  race_event               TEXT,
  race_date                TEXT,
  track_name               TEXT,
  track_conditions         TEXT,
  weather_conditions       TEXT,
  upper_bar_chassis_x      NUMERIC DEFAULT 32,
  upper_bar_chassis_y      NUMERIC DEFAULT 18.5,
  upper_bar_rear_x         NUMERIC DEFAULT 6,
  upper_bar_rear_y         NUMERIC DEFAULT 14,
  lower_bar_chassis_x      NUMERIC DEFAULT 38,
  lower_bar_chassis_y      NUMERIC DEFAULT 8.5,
  lower_bar_rear_x         NUMERIC DEFAULT 2,
  lower_bar_rear_y         NUMERIC DEFAULT 10,
  rear_end_center_height   NUMERIC DEFAULT 11,
  instant_center_length    NUMERIC,
  instant_center_height    NUMERIC,
  anti_squat_percentage    NUMERIC,
  corner_weights           JSONB DEFAULT '{"lf":850,"rf":850,"lr":1100,"rr":1100}'::jsonb,
  ballast_items            JSONB DEFAULT '[]'::jsonb,
  total_weight             NUMERIC,
  cross_weight_percentage  NUMERIC,
  shock_settings           JSONB DEFAULT '{"lf":{"compression":6,"rebound":8,"gasCharge":150,"model":""},"rf":{"compression":6,"rebound":8,"gasCharge":150,"model":""},"lr":{"compression":4,"rebound":6,"gasCharge":200,"model":""},"rr":{"compression":4,"rebound":6,"gasCharge":200,"model":""}}'::jsonb,
  ride_heights             JSONB DEFAULT '{"frontLeft":4.5,"frontRight":4.5,"rearLeft":5.0,"rearRight":5.0,"pinionAngle":-2.5}'::jsonb,
  spring_data              JSONB DEFAULT '{"lf":{"rate":250,"preload":1.5,"freeLength":10},"rf":{"rate":250,"preload":1.5,"freeLength":10},"lr":{"rate":175,"preload":2.0,"freeLength":12},"rr":{"rate":175,"preload":2.0,"freeLength":12}}'::jsonb,
  cg_data                  JSONB,
  pinion_data              JSONB,
  performance_notes        TEXT,
  sixty_foot_time          NUMERIC,
  eighth_mile_et           NUMERIC,
  eighth_mile_mph          NUMERIC,
  quarter_mile_et          NUMERIC,
  quarter_mile_mph         NUMERIC,
  is_favorite              BOOLEAN DEFAULT FALSE,
  tags                     JSONB DEFAULT '[]'::jsonb,
  car_id                   TEXT,
  created_by               TEXT,
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  updated_at               TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.chassis_setups ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own chassis_setups' AND tablename = 'chassis_setups') THEN
    CREATE POLICY "Users manage own chassis_setups" ON public.chassis_setups FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 20. TRANSMISSIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.transmissions (
  id                  TEXT PRIMARY KEY,
  user_id             UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                TEXT NOT NULL,
  serial_number       TEXT,
  type                TEXT,
  model               TEXT,
  builder             TEXT,
  gear_count          INTEGER DEFAULT 2,
  install_date        TEXT,
  total_passes        INTEGER DEFAULT 0,
  status              TEXT DEFAULT 'Ready',
  currently_installed BOOLEAN DEFAULT FALSE,
  notes               TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.transmissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own transmissions' AND tablename = 'transmissions') THEN
    CREATE POLICY "Users manage own transmissions" ON public.transmissions FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 21. SETUP VENDORS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.setup_vendors (
  id               TEXT PRIMARY KEY,
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name             TEXT NOT NULL,
  code             TEXT,
  contact_name     TEXT,
  email            TEXT,
  phone            TEXT,
  address          TEXT,
  city             TEXT,
  state            TEXT,
  zip              TEXT,
  website          TEXT,
  category         TEXT,
  payment_terms    TEXT,
  discount_percent NUMERIC DEFAULT 0,
  lead_time_days   INTEGER DEFAULT 14,
  minimum_order    NUMERIC DEFAULT 0,
  shipping_method  TEXT,
  is_active        BOOLEAN DEFAULT TRUE,
  created_date     TEXT,
  notes            TEXT,
  rating           INTEGER DEFAULT 0,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.setup_vendors ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own setup_vendors' AND tablename = 'setup_vendors') THEN
    CREATE POLICY "Users manage own setup_vendors" ON public.setup_vendors FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 22. VENDOR INVOICES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.vendor_invoices (
  id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                  UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  vendor_id                TEXT,
  vendor_name              TEXT NOT NULL,
  invoice_number           TEXT NOT NULL,
  invoice_date             TEXT NOT NULL,
  due_date                 TEXT,
  amount                   NUMERIC DEFAULT 0,
  tax                      NUMERIC DEFAULT 0,
  total                    NUMERIC DEFAULT 0,
  status                   TEXT DEFAULT 'Pending',
  po_number                TEXT,
  file_url                 TEXT,
  file_name                TEXT,
  file_type                TEXT,
  file_size                BIGINT,
  notes                    TEXT,
  category                 TEXT,
  payment_method           TEXT,
  payment_date             TEXT,
  paid_date                TEXT,
  receipt_url              TEXT,
  linked_event_id          TEXT,
  linked_event_name        TEXT,
  linked_work_order_id     TEXT,
  linked_work_order_title  TEXT,
  car_id                   TEXT,
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  updated_at               TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.vendor_invoices ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own vendor_invoices' AND tablename = 'vendor_invoices') THEN
    CREATE POLICY "Users manage own vendor_invoices" ON public.vendor_invoices FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 23. INVOICE LINE ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.invoice_line_items (
  id                        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                   UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  invoice_id                UUID NOT NULL,
  description               TEXT,
  part_number               TEXT,
  category                  TEXT,
  quantity                  NUMERIC DEFAULT 1,
  unit_cost                 NUMERIC DEFAULT 0,
  unit_price                NUMERIC DEFAULT 0,
  total                     NUMERIC DEFAULT 0,
  vendor_part_number        TEXT,
  notes                     TEXT,
  auto_created_inventory_id TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW(),
  updated_at                TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.invoice_line_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own invoice_line_items' AND tablename = 'invoice_line_items') THEN
    CREATE POLICY "Users manage own invoice_line_items" ON public.invoice_line_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 24. COST REPORTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cost_reports (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  invoice_id    UUID,
  vendor_name   TEXT NOT NULL,
  amount        NUMERIC DEFAULT 0,
  category      TEXT,
  date          TEXT NOT NULL,
  description   TEXT,
  source        TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cost_reports ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own cost_reports' AND tablename = 'cost_reports') THEN
    CREATE POLICY "Users manage own cost_reports" ON public.cost_reports FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 25. TODO ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.todo_items (
  id               TEXT PRIMARY KEY,
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title            TEXT NOT NULL,
  description      TEXT,
  priority         TEXT DEFAULT 'Medium',
  status           TEXT DEFAULT 'Pending',
  category         TEXT DEFAULT 'General',
  assigned_to      TEXT,
  created_by       TEXT,
  created_by_role  TEXT,
  due_date         TEXT,
  completed_date   TEXT,
  completed_by     TEXT,
  tags             JSONB DEFAULT '[]'::jsonb,
  is_archived      BOOLEAN DEFAULT FALSE,
  archived_at      TEXT,
  archived_by      TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.todo_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own todo_items' AND tablename = 'todo_items') THEN
    CREATE POLICY "Users manage own todo_items" ON public.todo_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 26. USER SETTINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_settings (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  feature     TEXT NOT NULL,
  settings    JSONB DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, feature)
);

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own user_settings' AND tablename = 'user_settings') THEN
    CREATE POLICY "Users manage own user_settings" ON public.user_settings FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 27. TEAM NOTES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_notes (
  id          TEXT PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title       TEXT NOT NULL,
  content     TEXT,
  category    TEXT DEFAULT 'General',
  created_by  TEXT,
  is_pinned   BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.team_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own team_notes' AND tablename = 'team_notes') THEN
    CREATE POLICY "Users manage own team_notes" ON public.team_notes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 28. LABOR ENTRIES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.labor_entries (
  id                TEXT PRIMARY KEY,
  user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  team_member_id    TEXT,
  team_member_name  TEXT NOT NULL,
  date              TEXT NOT NULL,
  hours             NUMERIC DEFAULT 0,
  hourly_rate       NUMERIC DEFAULT 125,
  daily_rate        NUMERIC,
  rate_type         TEXT DEFAULT 'hourly',
  total_cost        NUMERIC DEFAULT 0,
  description       TEXT,
  category          TEXT DEFAULT 'Shop Work',
  notes             TEXT,
  event_id          TEXT,
  event_name        TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.labor_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own labor_entries' AND tablename = 'labor_entries') THEN
    CREATE POLICY "Users manage own labor_entries" ON public.labor_entries FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 29. RACE CARS (multi-car support)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.race_cars (
  id          TEXT PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  car_number  TEXT,
  nickname    TEXT,
  name        TEXT,
  class       TEXT,
  class_type  TEXT,
  year        INTEGER,
  make        TEXT,
  model       TEXT,
  color       TEXT,
  vin         TEXT,
  weight      NUMERIC,
  photo_url   TEXT,
  is_active   BOOLEAN DEFAULT TRUE,
  notes       TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.race_cars ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own race_cars' AND tablename = 'race_cars') THEN
    CREATE POLICY "Users manage own race_cars" ON public.race_cars FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 30. DRIVETRAIN COMPONENTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.drivetrain_components (
  id                    TEXT PRIMARY KEY,
  user_id               UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  category              TEXT NOT NULL,
  name                  TEXT,
  make                  TEXT,
  model                 TEXT,
  serial_number         TEXT,
  builder               TEXT,
  install_date          TEXT,
  date_removed          TEXT,
  total_passes          INTEGER DEFAULT 0,
  passes_since_service  INTEGER DEFAULT 0,
  hours                 NUMERIC DEFAULT 0,
  status                TEXT DEFAULT 'Ready',
  currently_installed   BOOLEAN DEFAULT FALSE,
  notes                 TEXT,
  components            JSONB DEFAULT '{}'::jsonb,
  car_id                TEXT,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.drivetrain_components ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own drivetrain_components' AND tablename = 'drivetrain_components') THEN
    CREATE POLICY "Users manage own drivetrain_components" ON public.drivetrain_components FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 31. DRIVETRAIN SWAP LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.drivetrain_swap_logs (
  id                      TEXT PRIMARY KEY,
  user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date                    TEXT NOT NULL,
  time                    TEXT,
  component_type          TEXT NOT NULL,
  previous_component_id   TEXT,
  new_component_id        TEXT,
  previous_component_name TEXT,
  new_component_name      TEXT,
  reason                  TEXT,
  performed_by            TEXT,
  notes                   TEXT,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.drivetrain_swap_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own drivetrain_swap_logs' AND tablename = 'drivetrain_swap_logs') THEN
    CREATE POLICY "Users manage own drivetrain_swap_logs" ON public.drivetrain_swap_logs FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 32. FUEL LOG ENTRIES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fuel_log_entries (
  id                TEXT PRIMARY KEY,
  user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  team_id           UUID,
  car_id            TEXT,
  date              TEXT NOT NULL,
  fuel_type         TEXT DEFAULT 'Methanol',
  quantity_gallons  NUMERIC DEFAULT 0,
  price_per_gallon  NUMERIC DEFAULT 0,
  total_cost        NUMERIC DEFAULT 0,
  vendor            TEXT,
  notes             TEXT,
  race_event_id     TEXT,
  linked_event_name TEXT,
  gallons_used      NUMERIC,
  passes_at_event   INTEGER,
  receipt_number    TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fuel_log_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own fuel_log_entries' AND tablename = 'fuel_log_entries') THEN
    CREATE POLICY "Users manage own fuel_log_entries" ON public.fuel_log_entries FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 33. TEAM INVITES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_invites (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_owner_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email           TEXT NOT NULL,
  role            TEXT DEFAULT 'Crew',
  permissions     JSONB DEFAULT '["view"]'::jsonb,
  token           TEXT NOT NULL,
  status          TEXT DEFAULT 'pending',
  invited_by_name TEXT,
  team_name       TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  expires_at      TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days'),
  accepted_at     TIMESTAMPTZ
);

ALTER TABLE public.team_invites ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Owners manage own team_invites' AND tablename = 'team_invites') THEN
    CREATE POLICY "Owners manage own team_invites" ON public.team_invites FOR ALL USING (auth.uid() = team_owner_id) WITH CHECK (auth.uid() = team_owner_id);
  END IF;
END $$;

-- ============================================================
-- 34. TEAM MEMBERSHIPS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_memberships (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_owner_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  team_member_id   TEXT,
  role             TEXT DEFAULT 'Crew',
  permissions      JSONB DEFAULT '["view"]'::jsonb,
  status           TEXT DEFAULT 'active',
  joined_at        TIMESTAMPTZ DEFAULT NOW(),
  invite_id        UUID,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.team_memberships ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Owners manage team_memberships' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Owners manage team_memberships" ON public.team_memberships FOR ALL USING (auth.uid() = team_owner_id) WITH CHECK (auth.uid() = team_owner_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members can view own memberships' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Members can view own memberships" ON public.team_memberships FOR SELECT USING (auth.uid() = member_user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members can insert own membership' AND tablename = 'team_memberships') THEN
    CREATE POLICY "Members can insert own membership" ON public.team_memberships FOR INSERT WITH CHECK (auth.uid() = member_user_id);
  END IF;
END $$;

-- ============================================================
-- 35. PARTS USAGE LOG
-- ============================================================
CREATE TABLE IF NOT EXISTS public.parts_usage_log (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  part_id          TEXT NOT NULL,
  part_number      TEXT NOT NULL,
  part_description TEXT,
  quantity_used    INTEGER DEFAULT 1,
  unit_cost        NUMERIC DEFAULT 0,
  total_cost       NUMERIC DEFAULT 0,
  usage_date       TEXT NOT NULL,
  usage_type       TEXT DEFAULT 'work_order',
  related_id       TEXT,
  related_title    TEXT,
  notes            TEXT,
  recorded_by      TEXT,
  previous_on_hand INTEGER DEFAULT 0,
  new_on_hand      INTEGER DEFAULT 0,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.parts_usage_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own parts_usage_log' AND tablename = 'parts_usage_log') THEN
    CREATE POLICY "Users manage own parts_usage_log" ON public.parts_usage_log FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 36. MISC EXPENSES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.misc_expenses (
  id                  TEXT PRIMARY KEY,
  user_id             UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  car_id              TEXT,
  category            TEXT NOT NULL,
  custom_description  TEXT,
  amount              NUMERIC NOT NULL,
  expense_date        TEXT NOT NULL,
  paid_by             TEXT,
  payment_method      TEXT,
  receipt_url         TEXT,
  receipt_file_name   TEXT,
  receipt_file_type   TEXT,
  receipt_file_size   INTEGER,
  notes               TEXT,
  race_event_id       TEXT,
  linked_event_name   TEXT,
  add_to_cost_report  BOOLEAN DEFAULT TRUE,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.misc_expenses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own misc_expenses' AND tablename = 'misc_expenses') THEN
    CREATE POLICY "Users manage own misc_expenses" ON public.misc_expenses FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 37. BORROWED / LOANED PARTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.borrowed_loaned_parts (
  id                    TEXT PRIMARY KEY,
  user_id               UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  transaction_type      TEXT NOT NULL,
  part_name             TEXT NOT NULL,
  part_number           TEXT,
  description           TEXT,
  quantity              INTEGER DEFAULT 1,
  person_name           TEXT,
  contact               TEXT,
  date_transaction      TEXT,
  expected_return_date  TEXT,
  actual_return_date    TEXT,
  condition_out         TEXT,
  condition_returned    TEXT,
  notes                 TEXT,
  status                TEXT DEFAULT 'active',
  linked_inventory_id   TEXT,
  inventory_adjusted    BOOLEAN DEFAULT FALSE,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.borrowed_loaned_parts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own borrowed_loaned_parts' AND tablename = 'borrowed_loaned_parts') THEN
    CREATE POLICY "Users manage own borrowed_loaned_parts" ON public.borrowed_loaned_parts FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================================
-- 38. CHASSIS SETUP USER PRESETS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.chassis_setup_user_presets (
  id                        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                   UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  name                      TEXT NOT NULL,
  description               TEXT,
  category                  TEXT NOT NULL,
  settings                  JSONB NOT NULL,
  recommended_pinion_angle  NUMERIC,
  target_anti_squat_min     NUMERIC,
  target_anti_squat_max     NUMERIC,
  characteristics           JSONB DEFAULT '[]'::jsonb,
  notes                     TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW(),
  updated_at                TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.chassis_setup_user_presets ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own chassis_setup_user_presets' AND tablename = 'chassis_setup_user_presets') THEN
    CREATE POLICY "Users manage own chassis_setup_user_presets" ON public.chassis_setup_user_presets FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;


-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_pass_logs_user_id        ON public.pass_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_pass_logs_date           ON public.pass_logs(date DESC);
CREATE INDEX IF NOT EXISTS idx_pass_logs_car_id         ON public.pass_logs(car_id);
CREATE INDEX IF NOT EXISTS idx_engines_user_id          ON public.engines(user_id);
CREATE INDEX IF NOT EXISTS idx_engines_car_id           ON public.engines(car_id);
CREATE INDEX IF NOT EXISTS idx_superchargers_user_id    ON public.superchargers(user_id);
CREATE INDEX IF NOT EXISTS idx_cylinder_heads_user_id   ON public.cylinder_heads(user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_user_id      ON public.maintenance_items(user_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_car_id       ON public.maintenance_items(car_id);
CREATE INDEX IF NOT EXISTS idx_sfi_certs_user_id        ON public.sfi_certifications(user_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_user_id      ON public.work_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_car_id       ON public.work_orders(car_id);
CREATE INDEX IF NOT EXISTS idx_checklists_user_id       ON public.checklists(user_id);
CREATE INDEX IF NOT EXISTS idx_checklists_type          ON public.checklists(checklist_type);
CREATE INDEX IF NOT EXISTS idx_parts_inv_user_id        ON public.parts_inventory(user_id);
CREATE INDEX IF NOT EXISTS idx_parts_inv_category       ON public.parts_inventory(category);
CREATE INDEX IF NOT EXISTS idx_parts_inv_drivetrain     ON public.parts_inventory(related_drivetrain_component_id);
CREATE INDEX IF NOT EXISTS idx_parts_inv_car_id         ON public.parts_inventory(car_id);
CREATE INDEX IF NOT EXISTS idx_race_events_user_id      ON public.race_events(user_id);
CREATE INDEX IF NOT EXISTS idx_race_events_date         ON public.race_events(start_date DESC);
CREATE INDEX IF NOT EXISTS idx_race_events_track_zip    ON public.race_events(track_zip);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id     ON public.team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_media_gallery_user_id    ON public.media_gallery(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_tracks_user_id     ON public.saved_tracks(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id       ON public.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp     ON public.audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chassis_setups_user_id   ON public.chassis_setups(user_id);
CREATE INDEX IF NOT EXISTS idx_transmissions_user_id    ON public.transmissions(user_id);
CREATE INDEX IF NOT EXISTS idx_setup_vendors_user_id    ON public.setup_vendors(user_id);
CREATE INDEX IF NOT EXISTS idx_vendor_invoices_user_id  ON public.vendor_invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_invoice_line_items_inv   ON public.invoice_line_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_cost_reports_user_id     ON public.cost_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_cost_reports_date        ON public.cost_reports(date DESC);
CREATE INDEX IF NOT EXISTS idx_swap_logs_user_id        ON public.engine_swap_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_weather_hist_user_id     ON public.track_weather_history(user_id);
CREATE INDEX IF NOT EXISTS idx_todo_items_user_id       ON public.todo_items(user_id);
CREATE INDEX IF NOT EXISTS idx_user_settings_user_id    ON public.user_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_team_notes_user_id       ON public.team_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_labor_entries_user_id    ON public.labor_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_labor_entries_date       ON public.labor_entries(date DESC);
CREATE INDEX IF NOT EXISTS idx_race_cars_user_id        ON public.race_cars(user_id);
CREATE INDEX IF NOT EXISTS idx_drivetrain_comp_user_id  ON public.drivetrain_components(user_id);
CREATE INDEX IF NOT EXISTS idx_drivetrain_comp_category ON public.drivetrain_components(category);
CREATE INDEX IF NOT EXISTS idx_drivetrain_swap_user_id  ON public.drivetrain_swap_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_user_id         ON public.fuel_log_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_team_id         ON public.fuel_log_entries(team_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_date            ON public.fuel_log_entries(date DESC);
CREATE INDEX IF NOT EXISTS idx_team_invites_owner       ON public.team_invites(team_owner_id);
CREATE INDEX IF NOT EXISTS idx_team_invites_token       ON public.team_invites(token);
CREATE INDEX IF NOT EXISTS idx_team_invites_email       ON public.team_invites(email);
CREATE INDEX IF NOT EXISTS idx_team_memberships_owner   ON public.team_memberships(team_owner_id);
CREATE INDEX IF NOT EXISTS idx_team_memberships_member  ON public.team_memberships(member_user_id);
CREATE INDEX IF NOT EXISTS idx_parts_usage_user_id      ON public.parts_usage_log(user_id);
CREATE INDEX IF NOT EXISTS idx_parts_usage_part_id      ON public.parts_usage_log(part_id);
CREATE INDEX IF NOT EXISTS idx_parts_usage_date         ON public.parts_usage_log(usage_date DESC);
CREATE INDEX IF NOT EXISTS idx_misc_expenses_user_id    ON public.misc_expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_misc_expenses_date       ON public.misc_expenses(expense_date DESC);
CREATE INDEX IF NOT EXISTS idx_borrowed_parts_user_id   ON public.borrowed_loaned_parts(user_id);
CREATE INDEX IF NOT EXISTS idx_borrowed_parts_status    ON public.borrowed_loaned_parts(status);
CREATE INDEX IF NOT EXISTS idx_chassis_presets_user_id  ON public.chassis_setup_user_presets(user_id);


-- ============================================================
-- RPC: INCREMENT TRACK VISIT COUNT
-- ============================================================
CREATE OR REPLACE FUNCTION public.increment_track_visit(track_id TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.saved_tracks
  SET visit_count = COALESCE(visit_count, 0) + 1,
      last_visited = TO_CHAR(NOW(), 'YYYY-MM-DD'),
      updated_at = NOW()
  WHERE id = track_id
    AND user_id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================================
-- HELPER FUNCTIONS FOR TEAM MEMBER DATA ACCESS
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_team_member_of(owner_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.team_memberships
    WHERE team_owner_id = owner_id
      AND member_user_id = auth.uid()
      AND status = 'active'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION public.has_team_edit_permission(owner_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.team_memberships
    WHERE team_owner_id = owner_id
      AND member_user_id = auth.uid()
      AND status = 'active'
      AND permissions ? 'edit'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;


-- ============================================================
-- STORAGE BUCKET FOR MEDIA
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'media',
  'media',
  true,
  52428800,
  ARRAY['image/jpeg','image/png','image/gif','image/webp','image/svg+xml','video/mp4','video/quicktime','video/webm','application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 52428800;

-- Storage RLS policies (drop-and-recreate for idempotency)
DO $$ BEGIN DROP POLICY IF EXISTS "Authenticated users can upload media" ON storage.objects; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS "Public read access to media" ON storage.objects; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS "Users can update own media files" ON storage.objects; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS "Users can delete own media files" ON storage.objects; EXCEPTION WHEN others THEN NULL; END $$;

CREATE POLICY "Authenticated users can upload media" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'media');
CREATE POLICY "Public read access to media" ON storage.objects FOR SELECT TO public USING (bucket_id = 'media');
CREATE POLICY "Users can update own media files" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'media');
CREATE POLICY "Users can delete own media files" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'media');


-- ============================================================
-- AUTO-CREATE PROFILE ON SIGNUP (TRIGGER)
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (id, user_id, team_name, contact_email, created_at, updated_at)
  VALUES (
    NEW.id,
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'team_name', 'My Race Team'),
    NEW.email,
    NOW(),
    NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    user_id = EXCLUDED.user_id
  WHERE public.user_profiles.user_id IS NULL;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- DONE!
-- ============================================================
-- All 38 tables, RLS policies, indexes, RPC functions,
-- helper functions, storage bucket, and auto-profile trigger
-- have been created.
--
-- You can verify by running:
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public'
--   ORDER BY table_name;
-- ============================================================
