import React, { useState, useEffect, useMemo } from 'react';
import DateInputDark from '@/components/ui/DateInputDark';
import CarDropdown from '@/components/race/CarDropdown';
import { useCar } from '@/contexts/CarContext';

import { useApp } from '@/contexts/AppContext';

import { PartInventoryItem } from '@/data/partsInventory';
import { partsUsageHistory, PartUsageRecord, getUsageByPart } from '@/data/partsUsageData';
import { VendorRecord } from '@/lib/database';
import { WorkOrder, ComponentTracker, Supercharger } from '@/data/proModData';



import {
  Wrench,
  Plus,
  Clock,
  DollarSign,
  Package,
  AlertTriangle,
  CheckCircle2,
  PlayCircle,
  PauseCircle,
  X,
  Edit2,
  Trash2,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  FileText,
  Calendar,
  User,
  Settings,
  Zap,
  Wind,
  ShoppingCart,
  Timer,
  TrendingUp,
  Filter,
  Search,
  History,
  ArrowDownCircle,
  PackagePlus
} from 'lucide-react';


interface EnhancedWorkOrder extends WorkOrder {
  laborEntries?: LaborEntry[];
  totalLaborCost?: number;
  totalPartsCost?: number;
  totalCost?: number;
  estimatedCost?: number;
  partsFromInventory?: { partId: string; quantity: number; reserved: boolean }[];
  autoGenerated?: boolean;
  sourceComponent?: {
    type: 'engine' | 'head' | 'supercharger' | 'maintenance';
    parentId: string;
    componentKey?: string;
  };
}

interface LaborEntry {
  id: string;
  startTime: string;
  endTime?: string;
  duration?: number;
  technician: string;
  notes: string;
  hourlyRate: number;
}

interface ServiceAlert {
  id: string;
  componentName: string;
  parentName: string;
  parentType: 'engine' | 'head' | 'supercharger' | 'maintenance';
  parentId: string;
  componentKey?: string;
  serviceType: 'inspect' | 'service' | 'replace';
  passCount: number;
  interval: number;
  urgency: 'low' | 'medium' | 'high' | 'critical';
  suggestedParts: string[];
}

// Local storage for parts usage records created from work orders
const localPartsUsageRecords: PartUsageRecord[] = [];

const WorkOrderSystem: React.FC = () => {
  const {
    workOrders,
    addWorkOrder,
    updateWorkOrder,
    deleteWorkOrder,
    engines,
    cylinderHeads,
    superchargers,
    maintenanceItems,
    partsInventory,
    updatePartInventory,
    addPartInventory,
    teamMembers,
    passLogs,
    vendors: allVendors
  } = useApp();

  const { selectedCarId, getCarLabel } = useCar();

  // Active vendors derived from centralized AppContext (no more independent fetching)
  const vendorsList = useMemo(() => allVendors.filter((v: VendorRecord) => v.isActive), [allVendors]);

  const DEFAULT_HOURLY_RATE = 75;

  // ─── State ─────────────────────────────────────────────────────────
  const [activeTab, setActiveTab] = useState<'dashboard' | 'all' | 'auto-generate' | 'parts'>('dashboard');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editingWorkOrder, setEditingWorkOrder] = useState<EnhancedWorkOrder | null>(null);
  const [selectedWorkOrder, setSelectedWorkOrder] = useState<EnhancedWorkOrder | null>(null);

  const [showDetailModal, setShowDetailModal] = useState(false);
  const [serviceAlerts, setServiceAlerts] = useState<ServiceAlert[]>([]);
  const [activeLaborEntry, setActiveLaborEntry] = useState<{ workOrderId: string; entry: LaborEntry } | null>(null);
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterPriority, setFilterPriority] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [showUsageHistoryModal, setShowUsageHistoryModal] = useState(false);
  const [selectedWorkOrderForHistory, setSelectedWorkOrderForHistory] = useState<string | null>(null);
  const [woVendor, setWoVendor] = useState('');


  // Calculate service alerts from components
  useEffect(() => {
    const alerts: ServiceAlert[] = [];

    engines.forEach(engine => {
      if (engine.components) {
        Object.entries(engine.components).forEach(([key, comp]) => {
          const component = comp as ComponentTracker;
          if (component.status === 'Inspect' || component.status === 'Service' || component.status === 'Replace') {
            alerts.push({
              id: `${engine.id}-${key}`,
              componentName: component.name,
              parentName: engine.name,
              parentType: 'engine',
              parentId: engine.id,
              componentKey: key,
              serviceType: component.status === 'Replace' ? 'replace' : component.status === 'Service' ? 'service' : 'inspect',
              passCount: component.passCount,
              interval: component.status === 'Replace' ? component.replaceInterval : 
                       component.status === 'Service' ? component.serviceInterval : component.inspectionInterval,
              urgency: component.status === 'Replace' ? 'critical' : 
                      component.status === 'Service' ? 'high' : 'medium',
              suggestedParts: getSuggestedParts(component.name, component.partNumber)
            });
          }
        });
      }
    });

    cylinderHeads.forEach(head => {
      if (head.components) {
        Object.entries(head.components).forEach(([key, comp]) => {
          const component = comp as ComponentTracker;
          if (component.status === 'Inspect' || component.status === 'Service' || component.status === 'Replace') {
            alerts.push({
              id: `${head.id}-${key}`,
              componentName: component.name,
              parentName: head.name,
              parentType: 'head',
              parentId: head.id,
              componentKey: key,
              serviceType: component.status === 'Replace' ? 'replace' : component.status === 'Service' ? 'service' : 'inspect',
              passCount: component.passCount,
              interval: component.status === 'Replace' ? component.replaceInterval : 
                       component.status === 'Service' ? component.serviceInterval : component.inspectionInterval,
              urgency: component.status === 'Replace' ? 'critical' : 
                      component.status === 'Service' ? 'high' : 'medium',
              suggestedParts: getSuggestedParts(component.name, component.partNumber)
            });
          }
        });
      }
    });

    superchargers.forEach(sc => {
      const scWithComponents = sc as Supercharger & { components?: Record<string, ComponentTracker> };
      if (scWithComponents.components) {
        Object.entries(scWithComponents.components).forEach(([key, comp]) => {

          const component = comp as ComponentTracker;
          if (component.status === 'Inspect' || component.status === 'Service' || component.status === 'Replace') {
            alerts.push({
              id: `${sc.id}-${key}`,
              componentName: component.name,
              parentName: sc.name,
              parentType: 'supercharger',
              parentId: sc.id,
              componentKey: key,
              serviceType: component.status === 'Replace' ? 'replace' : component.status === 'Service' ? 'service' : 'inspect',
              passCount: component.passCount,
              interval: component.status === 'Replace' ? component.replaceInterval : 
                       component.status === 'Service' ? component.serviceInterval : component.inspectionInterval,
              urgency: component.status === 'Replace' ? 'critical' : 
                      component.status === 'Service' ? 'high' : 'medium',
              suggestedParts: getSuggestedParts(component.name, component.partNumber)
            });
          }
        });
      }
    });

    maintenanceItems.forEach(item => {
      if (item.status === 'Due' || item.status === 'Overdue' || item.status === 'Due Soon') {
        alerts.push({
          id: `maint-${item.id}`,
          componentName: item.component,
          parentName: item.category,
          parentType: 'maintenance',
          parentId: item.id,
          serviceType: 'service',
          passCount: item.currentPasses,
          interval: item.passInterval,
          urgency: item.status === 'Overdue' ? 'critical' : item.status === 'Due' ? 'high' : 'medium',
          suggestedParts: getSuggestedParts(item.component, '')
        });
      }
    });

    setServiceAlerts(alerts.sort((a, b) => {
      const urgencyOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      return urgencyOrder[a.urgency] - urgencyOrder[b.urgency];
    }));
  }, [engines, cylinderHeads, superchargers, maintenanceItems]);

  const getSuggestedParts = (componentName: string, partNumber?: string): string[] => {
    const suggestions: string[] = [];
    const lowerName = componentName.toLowerCase();

    partsInventory.forEach(part => {
      const lowerDesc = part.description.toLowerCase();
      const lowerPartNum = part.partNumber.toLowerCase();

      if (partNumber && lowerPartNum.includes(partNumber.toLowerCase())) {
        suggestions.push(part.id);
      } else if (
        lowerDesc.includes(lowerName) ||
        (lowerName.includes('bearing') && lowerDesc.includes('bearing')) ||
        (lowerName.includes('valve') && lowerDesc.includes('valve')) ||
        (lowerName.includes('spring') && lowerDesc.includes('spring')) ||
        (lowerName.includes('piston') && lowerDesc.includes('piston')) ||
        (lowerName.includes('ring') && lowerDesc.includes('ring')) ||
        (lowerName.includes('rod') && lowerDesc.includes('rod')) ||
        (lowerName.includes('cam') && lowerDesc.includes('cam')) ||
        (lowerName.includes('lifter') && lowerDesc.includes('lifter'))
      ) {
        suggestions.push(part.id);
      }
    });

    return suggestions.slice(0, 5);
  };

  const filteredWorkOrders = useMemo(() => {
    return workOrders.filter(wo => {
      // Car filter: when no car selected show ALL; when car selected show matching + legacy (no car_id)
      const carId = wo.car_id;

      const matchesCar = !selectedCarId || selectedCarId === '' || carId === selectedCarId || !carId || carId === '';
      if (!matchesCar) return false;

      if (filterStatus !== 'all' && wo.status !== filterStatus) return false;
      if (filterPriority !== 'all' && wo.priority !== filterPriority) return false;
      if (searchQuery) {
        const query = searchQuery.toLowerCase();
        return (
          wo.title.toLowerCase().includes(query) ||
          wo.description.toLowerCase().includes(query) ||
          wo.category.toLowerCase().includes(query)
        );
      }
      return true;
    });
  }, [workOrders, filterStatus, filterPriority, searchQuery, selectedCarId]);


  const stats = useMemo(() => {
    const pending = workOrders.filter(wo => wo.status === 'Open').length;
    const inProgress = workOrders.filter(wo => wo.status === 'In Progress').length;
    const pendingParts = workOrders.filter(wo => wo.status === 'Pending Parts').length;
    const completed = workOrders.filter(wo => wo.status === 'Completed').length;
    const critical = workOrders.filter(wo => wo.priority === 'Critical' && wo.status !== 'Completed').length;

    const totalEstimatedCost = workOrders
      .filter(wo => wo.status !== 'Completed' && wo.status !== 'Cancelled')
      .reduce((sum, wo) => {
        const parts = Array.isArray(wo.parts) ? wo.parts : [];
        const partsCost = parts.reduce((ps, p) => ps + ((p.cost || 0) * (p.quantity || 0)), 0);
        const laborCost = (wo.estimatedHours || 0) * DEFAULT_HOURLY_RATE;
        return sum + partsCost + laborCost;
      }, 0);

    const totalActualCost = workOrders
      .filter(wo => wo.status === 'Completed')
      .reduce((sum, wo) => {
        const parts = Array.isArray(wo.parts) ? wo.parts : [];
        const partsCost = parts.reduce((ps, p) => ps + ((p.cost || 0) * (p.quantity || 0)), 0);
        const laborCost = ((wo.actualHours || wo.estimatedHours) || 0) * DEFAULT_HOURLY_RATE;
        return sum + partsCost + laborCost;
      }, 0);

    return { pending, inProgress, pendingParts, completed, critical, totalEstimatedCost, totalActualCost };
  }, [workOrders]);

  // Create parts usage records when work order is completed
  const createPartsUsageRecords = async (workOrder: WorkOrder) => {
    const parts = Array.isArray(workOrder.parts) ? workOrder.parts : [];
    
    for (const part of parts) {
      const inventoryPart = partsInventory.find(p => p.partNumber === part.partNumber);
      
      const usageRecord: PartUsageRecord = {
        id: `PU-WO-${workOrder.id}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        partId: inventoryPart?.id || '',
        partNumber: part.partNumber,
        partDescription: part.name,
        action: 'installed',
        date: new Date().toISOString().split('T')[0],
        time: new Date().toTimeString().slice(0, 5),
        installedOn: workOrder.category,
        passesAtAction: passLogs.length,

        installDate: new Date().toISOString().split('T')[0],
        workOrderId: workOrder.id,
        cost: part.cost || 0,
        laborHours: (workOrder.actualHours || workOrder.estimatedHours || 0) / parts.length,
        laborCost: ((workOrder.actualHours || workOrder.estimatedHours || 0) * DEFAULT_HOURLY_RATE) / parts.length,
        performedBy: workOrder.assignedTo || 'Unknown',
        notes: `Auto-generated from completed work order ${workOrder.id}: ${workOrder.title}`
      };

      // Add to local storage for tracking
      localPartsUsageRecords.push(usageRecord);
      
      // Update inventory - deduct the used parts
      if (inventoryPart && inventoryPart.onHand >= (part.quantity || 0)) {
        const newOnHand = inventoryPart.onHand - (part.quantity || 0);
        const newStatus: PartInventoryItem['status'] = newOnHand === 0 ? 'Out of Stock' : 
                         newOnHand <= inventoryPart.minQuantity ? 'Low Stock' : 'In Stock';
        
        await updatePartInventory(inventoryPart.id, {
          onHand: newOnHand,
          totalValue: newOnHand * inventoryPart.unitCost,
          status: newStatus,
          lastUsed: new Date().toISOString().split('T')[0]
        });

      }
    }
  };

  // Handle work order completion with parts usage integration
  const handleCompleteWorkOrder = async (workOrderId: string) => {
    const wo = workOrders.find(w => w.id === workOrderId);
    if (!wo) return;

    // Create parts usage records
    await createPartsUsageRecords(wo);

    // Update work order status
    await updateWorkOrder(workOrderId, { 
      status: 'Completed',
      completedDate: new Date().toISOString().split('T')[0]
    });
  };

  const generateWorkOrderFromAlert = async (alert: ServiceAlert) => {
    const suggestedPartsList = alert.suggestedParts.map(partId => {
      const part = partsInventory.find(p => p.id === partId);
      return part ? {
        name: part.description,
        partNumber: part.partNumber,
        quantity: 1,
        cost: part.unitCost
      } : null;
    }).filter(Boolean) as { name: string; partNumber: string; quantity: number; cost: number }[];

    const estimatedHours = alert.serviceType === 'replace' ? 4 : alert.serviceType === 'service' ? 2 : 1;

    const newWorkOrder: WorkOrder = {
      id: `WO-${String(workOrders.length + 1).padStart(3, '0')}`,
      title: `${alert.serviceType.charAt(0).toUpperCase() + alert.serviceType.slice(1)} ${alert.componentName}`,
      description: `${alert.serviceType === 'replace' ? 'Replace' : alert.serviceType === 'service' ? 'Service' : 'Inspect'} ${alert.componentName} on ${alert.parentName}. Component has ${alert.passCount} passes (interval: ${alert.interval}).`,
      category: alert.parentType === 'engine' ? 'Engine' : 
               alert.parentType === 'head' ? 'Cylinder Heads' : 
               alert.parentType === 'supercharger' ? 'Supercharger' : alert.parentName,
      priority: alert.urgency === 'critical' ? 'Critical' : 
               alert.urgency === 'high' ? 'High' : 
               alert.urgency === 'medium' ? 'Medium' : 'Low',
      status: 'Open',
      createdDate: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + (alert.urgency === 'critical' ? 3 : alert.urgency === 'high' ? 7 : 14) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      assignedTo: teamMembers.length > 0 ? teamMembers[0].name : 'Unassigned',
      estimatedHours,
      parts: suggestedPartsList,
      relatedComponent: alert.id,
      notes: `Auto-generated from service interval alert.`
    };

    await addWorkOrder(newWorkOrder);
  };

  const startLabor = (workOrderId: string, technician: string) => {
    const entry: LaborEntry = {
      id: `LABOR-${Date.now()}`,
      startTime: new Date().toISOString(),
      technician,
      notes: '',
      hourlyRate: DEFAULT_HOURLY_RATE
    };
    setActiveLaborEntry({ workOrderId, entry });
    updateWorkOrder(workOrderId, { status: 'In Progress' });
  };

  const stopLabor = async (notes: string) => {
    if (!activeLaborEntry) return;

    const endTime = new Date().toISOString();
    const startTime = new Date(activeLaborEntry.entry.startTime);
    const duration = Math.round((new Date(endTime).getTime() - startTime.getTime()) / 60000);

    const wo = workOrders.find(w => w.id === activeLaborEntry.workOrderId);
    if (wo) {
      const currentHours = wo.actualHours || 0;
      const newHours = currentHours + (duration / 60);
      await updateWorkOrder(activeLaborEntry.workOrderId, { actualHours: newHours });
    }

    setActiveLaborEntry(null);
  };

  const defaultWorkOrder: EnhancedWorkOrder = {
    id: '',
    title: '',
    description: '',
    category: 'General',
    priority: 'Medium',
    status: 'Open',
    createdDate: new Date().toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assignedTo: '',
    estimatedHours: 1,
    parts: [],
    notes: '',
    car_id: selectedCarId || '',
  };


  const [newWorkOrder, setNewWorkOrder] = useState<EnhancedWorkOrder>(defaultWorkOrder);
  const [newPart, setNewPart] = useState({ name: '', partNumber: '', quantity: 1, cost: 0 });
  const [selectedInventoryPart, setSelectedInventoryPart] = useState<string>('');
  const [partsEntryMode, setPartsEntryMode] = useState<'inventory' | 'manual'>('inventory');
  const [addedToInventoryParts, setAddedToInventoryParts] = useState<Set<string>>(new Set());


  const handleSaveWorkOrder = async () => {
    try {
      if (editingWorkOrder) {
        await updateWorkOrder(editingWorkOrder.id, newWorkOrder);
      } else {
        const id = `WO-${String(workOrders.length + 1).padStart(3, '0')}`;
        await addWorkOrder({ ...newWorkOrder, id });
      }
    } catch (error) {
      console.error('Error saving work order:', error);
    } finally {
      setShowCreateModal(false);
      setEditingWorkOrder(null);
      setNewWorkOrder(defaultWorkOrder);
    }
  };


  const handleAddPart = () => {
    if (selectedInventoryPart) {
      const part = partsInventory.find(p => p.id === selectedInventoryPart);
      if (part) {
        setNewWorkOrder({
          ...newWorkOrder,
          parts: [...newWorkOrder.parts, {
            name: part.description,
            partNumber: part.partNumber,
            quantity: newPart.quantity || 1,
            cost: part.unitCost
          }]
        });
        setSelectedInventoryPart('');
        setNewPart({ name: '', partNumber: '', quantity: 1, cost: 0 });
      }
    } else if (newPart.name) {
      setNewWorkOrder({
        ...newWorkOrder,
        parts: [...newWorkOrder.parts, { ...newPart }]
      });
      setNewPart({ name: '', partNumber: '', quantity: 1, cost: 0 });
    }
  };

  const handleRemovePart = (index: number) => {
    setNewWorkOrder({
      ...newWorkOrder,
      parts: newWorkOrder.parts.filter((_, i) => i !== index)
    });
  };

  // Add a manually-entered part to the parts inventory
  const handleAddPartToInventory = async (part: { name: string; partNumber: string; quantity: number; cost: number }) => {
    const partKey = `${part.partNumber || ''}-${part.name}`;
    // Check if already in inventory
    const existingPart = partsInventory.find(p => 
      (part.partNumber && p.partNumber === part.partNumber) || 
      p.description.toLowerCase() === part.name.toLowerCase()
    );
    if (existingPart) {
      alert(`Part "${part.name}" already exists in inventory as ${existingPart.partNumber}`);
      setAddedToInventoryParts(prev => new Set(prev).add(partKey));
      return;
    }

    const newId = `PART-${String(partsInventory.length + 1).padStart(4, '0')}`;
    const newPartNumber = part.partNumber || `WO-${newId}`;
    const today = new Date().toISOString().split('T')[0];
    
    const inventoryItem: PartInventoryItem = {
      id: newId,
      partNumber: newPartNumber,
      description: part.name,
      category: newWorkOrder.category || 'General',
      subcategory: '',
      onHand: part.quantity || 0,
      minQuantity: 1,
      maxQuantity: 10,
      vendor: woVendor || '',
      vendorPartNumber: newPartNumber,
      unitCost: part.cost || 0,
      totalValue: (part.cost || 0) * (part.quantity || 0),
      lastOrdered: today,
      lastUsed: '',
      location: 'TBD',
      notes: `Added from Work Order: ${newWorkOrder.title || editingWorkOrder?.title || 'N/A'}`,
      status: part.quantity > 0 ? 'In Stock' : 'Out of Stock',
      reorderStatus: 'OK'
    };

    try {
      await addPartInventory(inventoryItem);
      setAddedToInventoryParts(prev => new Set(prev).add(partKey));
      alert(`"${part.name}" has been added to Parts Inventory as ${newPartNumber}`);
    } catch (err) {
      console.error('Failed to add part to inventory:', err);
      alert('Failed to add part to inventory. Please try again.');
    }
  };


  // Get usage history for a work order
  const getWorkOrderUsageHistory = (workOrderId: string): PartUsageRecord[] => {
    const fromGlobal = partsUsageHistory.filter(u => u.workOrderId === workOrderId);
    const fromLocal = localPartsUsageRecords.filter(u => u.workOrderId === workOrderId);
    return [...fromGlobal, ...fromLocal];
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Open': return 'bg-blue-500/20 text-blue-400 border-blue-500/50';
      case 'In Progress': return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50';
      case 'Pending Parts': return 'bg-orange-500/20 text-orange-400 border-orange-500/50';
      case 'Completed': return 'bg-green-500/20 text-green-400 border-green-500/50';
      case 'Cancelled': return 'bg-slate-500/20 text-slate-400 border-slate-500/50';
      default: return 'bg-slate-500/20 text-slate-400 border-slate-500/50';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Critical': return 'bg-red-500/20 text-red-400';
      case 'High': return 'bg-orange-500/20 text-orange-400';
      case 'Medium': return 'bg-yellow-500/20 text-yellow-400';
      case 'Low': return 'bg-green-500/20 text-green-400';
      default: return 'bg-slate-500/20 text-slate-400';
    }
  };

  const getUrgencyColor = (urgency: string) => {
    switch (urgency) {
      case 'critical': return 'bg-red-500/20 text-red-400 border-red-500/50';
      case 'high': return 'bg-orange-500/20 text-orange-400 border-orange-500/50';
      case 'medium': return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50';
      case 'low': return 'bg-green-500/20 text-green-400 border-green-500/50';
      default: return 'bg-slate-500/20 text-slate-400 border-slate-500/50';
    }
  };

  return (
    <section className="py-8 px-4">
      <div className="max-w-[1920px] mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <h2 className="text-2xl font-bold text-white">Work Order System</h2>
            <p className="text-slate-400">Manage maintenance, track labor, and control costs</p>
          </div>
          <button
            onClick={() => {
              setEditingWorkOrder(null);
              setNewWorkOrder(defaultWorkOrder);
              setShowCreateModal(true);
            }}
            className="flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg font-medium hover:bg-orange-600 transition-colors"
          >
            <Plus className="w-4 h-4" />
            New Work Order
          </button>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-6 overflow-x-auto">
          <button
            onClick={() => setActiveTab('dashboard')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${
              activeTab === 'dashboard' ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
            }`}
          >
            <TrendingUp className="w-4 h-4" />
            Dashboard
          </button>
          <button
            onClick={() => setActiveTab('all')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${
              activeTab === 'all' ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
            }`}
          >
            <FileText className="w-4 h-4" />
            All Work Orders ({workOrders.length})
          </button>
          <button
            onClick={() => setActiveTab('auto-generate')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${
              activeTab === 'auto-generate' ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
            }`}
          >
            <RefreshCw className="w-4 h-4" />
            Service Alerts ({serviceAlerts.length})
          </button>
          <button
            onClick={() => setActiveTab('parts')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${
              activeTab === 'parts' ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
            }`}
          >
            <Package className="w-4 h-4" />
            Parts Needed
          </button>
        </div>

        {/* Dashboard Tab */}
        {activeTab === 'dashboard' && (
          <div className="space-y-6">
            {/* Stats Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4">
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center">
                    <FileText className="w-5 h-5 text-blue-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">{stats.pending}</p>
                    <p className="text-xs text-slate-400">Open</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-yellow-500/20 flex items-center justify-center">
                    <PlayCircle className="w-5 h-5 text-yellow-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">{stats.inProgress}</p>
                    <p className="text-xs text-slate-400">In Progress</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-orange-500/20 flex items-center justify-center">
                    <Package className="w-5 h-5 text-orange-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">{stats.pendingParts}</p>
                    <p className="text-xs text-slate-400">Pending Parts</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-green-500/20 flex items-center justify-center">
                    <CheckCircle2 className="w-5 h-5 text-green-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">{stats.completed}</p>
                    <p className="text-xs text-slate-400">Completed</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-red-500/30">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-red-500/20 flex items-center justify-center">
                    <AlertTriangle className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-red-400">{stats.critical}</p>
                    <p className="text-xs text-slate-400">Critical</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-purple-500/20 flex items-center justify-center">
                    <DollarSign className="w-5 h-5 text-purple-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">${stats.totalEstimatedCost.toLocaleString()}</p>
                    <p className="text-xs text-slate-400">Est. Cost</p>
                  </div>
                </div>
              </div>
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-cyan-500/20 flex items-center justify-center">
                    <Timer className="w-5 h-5 text-cyan-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-white">{serviceAlerts.length}</p>
                    <p className="text-xs text-slate-400">Service Alerts</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Active Labor Tracking */}
            {activeLaborEntry && (
              <div className="bg-green-500/10 border border-green-500/30 rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-lg bg-green-500/20 flex items-center justify-center animate-pulse">
                      <Timer className="w-6 h-6 text-green-400" />
                    </div>
                    <div>
                      <p className="text-white font-medium">Labor Timer Active</p>
                      <p className="text-sm text-slate-400">
                        {workOrders.find(w => w.id === activeLaborEntry.workOrderId)?.title} - {activeLaborEntry.entry.technician}
                      </p>
                      <p className="text-xs text-green-400">Started: {new Date(activeLaborEntry.entry.startTime).toLocaleTimeString()}</p>
                    </div>
                  </div>
                  <button
                    onClick={() => stopLabor('')}
                    className="flex items-center gap-2 px-4 py-2 bg-red-500 text-white rounded-lg font-medium hover:bg-red-600"
                  >
                    <PauseCircle className="w-4 h-4" />
                    Stop Timer
                  </button>
                </div>
              </div>
            )}

            {/* Recent Work Orders by Status */}
            <div className="grid md:grid-cols-3 gap-6">
              {/* Open */}
              <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden">
                <div className="p-4 border-b border-slate-700/50 bg-blue-500/10">
                  <h3 className="font-semibold text-white flex items-center gap-2">
                    <FileText className="w-4 h-4 text-blue-400" />
                    Open ({stats.pending})
                  </h3>
                </div>
                <div className="p-4 space-y-3 max-h-80 overflow-y-auto">
                  {workOrders.filter(wo => wo.status === 'Open').slice(0, 5).map(wo => (
                    <div
                      key={wo.id}
                      onClick={() => {
                        setSelectedWorkOrder(wo);
                        setShowDetailModal(true);
                      }}
                      className="p-3 bg-slate-900/50 rounded-lg cursor-pointer hover:bg-slate-700/50 transition-colors"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <p className="text-white font-medium text-sm">{wo.title}</p>
                          <p className="text-xs text-slate-400">{wo.category}</p>
                        </div>
                        <span className={`px-2 py-0.5 rounded text-xs font-medium ${getPriorityColor(wo.priority)}`}>
                          {wo.priority}
                        </span>
                      </div>
                    </div>
                  ))}
                  {workOrders.filter(wo => wo.status === 'Open').length === 0 && (
                    <p className="text-slate-500 text-sm text-center py-4">No open work orders</p>
                  )}
                </div>
              </div>

              {/* In Progress */}
              <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden">
                <div className="p-4 border-b border-slate-700/50 bg-yellow-500/10">
                  <h3 className="font-semibold text-white flex items-center gap-2">
                    <PlayCircle className="w-4 h-4 text-yellow-400" />
                    In Progress ({stats.inProgress})
                  </h3>
                </div>
                <div className="p-4 space-y-3 max-h-80 overflow-y-auto">
                  {workOrders.filter(wo => wo.status === 'In Progress').slice(0, 5).map(wo => (
                    <div
                      key={wo.id}
                      onClick={() => {
                        setSelectedWorkOrder(wo);
                        setShowDetailModal(true);
                      }}
                      className="p-3 bg-slate-900/50 rounded-lg cursor-pointer hover:bg-slate-700/50 transition-colors"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <p className="text-white font-medium text-sm">{wo.title}</p>
                          <p className="text-xs text-slate-400">{wo.assignedTo}</p>
                        </div>
                        <span className={`px-2 py-0.5 rounded text-xs font-medium ${getPriorityColor(wo.priority)}`}>
                          {wo.priority}
                        </span>
                      </div>
                      {wo.actualHours !== undefined && (
                        <div className="mt-2 flex items-center gap-2 text-xs text-slate-400">
                          <Clock className="w-3 h-3" />
                          {wo.actualHours.toFixed(1)}h / {wo.estimatedHours}h
                        </div>
                      )}
                    </div>
                  ))}
                  {workOrders.filter(wo => wo.status === 'In Progress').length === 0 && (
                    <p className="text-slate-500 text-sm text-center py-4">No work orders in progress</p>
                  )}
                </div>
              </div>

              {/* Pending Parts */}
              <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden">
                <div className="p-4 border-b border-slate-700/50 bg-orange-500/10">
                  <h3 className="font-semibold text-white flex items-center gap-2">
                    <Package className="w-4 h-4 text-orange-400" />
                    Pending Parts ({stats.pendingParts})
                  </h3>
                </div>
                <div className="p-4 space-y-3 max-h-80 overflow-y-auto">
                  {workOrders.filter(wo => wo.status === 'Pending Parts').slice(0, 5).map(wo => (
                    <div
                      key={wo.id}
                      onClick={() => {
                        setSelectedWorkOrder(wo);
                        setShowDetailModal(true);
                      }}
                      className="p-3 bg-slate-900/50 rounded-lg cursor-pointer hover:bg-slate-700/50 transition-colors"
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <p className="text-white font-medium text-sm">{wo.title}</p>
                          <p className="text-xs text-slate-400">{(wo.parts || []).length} parts needed</p>
                        </div>
                        <span className={`px-2 py-0.5 rounded text-xs font-medium ${getPriorityColor(wo.priority)}`}>
                          {wo.priority}
                        </span>
                      </div>
                    </div>
                  ))}
                  {workOrders.filter(wo => wo.status === 'Pending Parts').length === 0 && (
                    <p className="text-slate-500 text-sm text-center py-4">No work orders pending parts</p>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* All Work Orders Tab */}
        {activeTab === 'all' && (
          <div className="space-y-4">
            {/* Filters */}
            <div className="flex flex-wrap gap-4 items-center">
              <div className="flex-1 min-w-[200px]">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                  <input
                    type="text"
                    placeholder="Search work orders..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full bg-slate-800 border border-slate-600 rounded-lg pl-10 pr-4 py-2 text-white"
                  />
                </div>
              </div>
              <select
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value)}
                className="bg-slate-800 border border-slate-600 rounded-lg px-4 py-2 text-white"
              >
                <option value="all">All Status</option>
                <option value="Open">Open</option>
                <option value="In Progress">In Progress</option>
                <option value="Pending Parts">Pending Parts</option>
                <option value="Completed">Completed</option>
                <option value="Cancelled">Cancelled</option>
              </select>
              <select
                value={filterPriority}
                onChange={(e) => setFilterPriority(e.target.value)}
                className="bg-slate-800 border border-slate-600 rounded-lg px-4 py-2 text-white"
              >
                <option value="all">All Priority</option>
                <option value="Critical">Critical</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
              </select>
            </div>

            {/* Work Orders List */}
            <div className="space-y-3">
              {filteredWorkOrders.map(wo => {
                const woParts = Array.isArray(wo.parts) ? wo.parts : [];
                const partsCost = woParts.reduce((sum, p) => sum + ((p.cost || 0) * (p.quantity || 0)), 0);
                const laborCost = ((wo.actualHours || wo.estimatedHours) || 0) * DEFAULT_HOURLY_RATE;
                const totalCost = partsCost + laborCost;
                const usageHistory = getWorkOrderUsageHistory(wo.id);

                return (
                  <div
                    key={wo.id}
                    className="bg-slate-800/50 rounded-xl border border-slate-700/50 p-4 hover:border-slate-600/50 transition-colors"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-slate-500 text-sm font-mono">{wo.id}</span>
                          <span className={`px-2 py-0.5 rounded text-xs font-medium border ${getStatusColor(wo.status)}`}>
                            {wo.status}
                          </span>
                          <span className={`px-2 py-0.5 rounded text-xs font-medium ${getPriorityColor(wo.priority)}`}>
                            {wo.priority}
                          </span>
                          {usageHistory.length > 0 && (
                            <span className="px-2 py-0.5 bg-purple-500/20 text-purple-400 rounded text-xs flex items-center gap-1">
                              <History className="w-3 h-3" />
                              {usageHistory.length} usage records
                            </span>
                          )}
                        </div>
                        <h3 className="text-lg font-semibold text-white mb-1">{wo.title}</h3>
                        <p className="text-sm text-slate-400 mb-3">{wo.description}</p>
                        
                        <div className="flex flex-wrap gap-4 text-sm">
                          <div className="flex items-center gap-2 text-slate-400">
                            <User className="w-4 h-4" />
                            {wo.assignedTo}
                          </div>
                          <div className="flex items-center gap-2 text-slate-400">
                            <Calendar className="w-4 h-4" />
                            Due: {wo.dueDate}
                          </div>
                          <div className="flex items-center gap-2 text-slate-400">
                            <Clock className="w-4 h-4" />
                            {wo.actualHours?.toFixed(1) || '0'}h / {wo.estimatedHours}h
                          </div>
                          <div className="flex items-center gap-2 text-slate-400">
                            <Package className="w-4 h-4" />
                            {woParts.length} parts
                          </div>
                          <div className="flex items-center gap-2 text-slate-400">
                            <DollarSign className="w-4 h-4" />
                            ${totalCost.toLocaleString()}
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center gap-2 ml-4">
                        {wo.status !== 'Completed' && wo.status !== 'Cancelled' && !activeLaborEntry && (
                          <button
                            onClick={() => startLabor(wo.id, teamMembers[0]?.name || 'Technician')}
                            className="p-2 bg-green-500/20 text-green-400 rounded-lg hover:bg-green-500/30"
                            title="Start Labor Timer"
                          >
                            <PlayCircle className="w-5 h-5" />
                          </button>
                        )}
                        {wo.status === 'In Progress' && (
                          <button
                            onClick={() => handleCompleteWorkOrder(wo.id)}
                            className="p-2 bg-green-500/20 text-green-400 rounded-lg hover:bg-green-500/30"
                            title="Complete & Create Usage Records"
                          >
                            <CheckCircle2 className="w-5 h-5" />
                          </button>
                        )}
                        {usageHistory.length > 0 && (
                          <button
                            onClick={() => {
                              setSelectedWorkOrderForHistory(wo.id);
                              setShowUsageHistoryModal(true);
                            }}
                            className="p-2 bg-purple-500/20 text-purple-400 rounded-lg hover:bg-purple-500/30"
                            title="View Usage History"
                          >
                            <History className="w-5 h-5" />
                          </button>
                        )}
                        <button
                          onClick={() => {
                            setSelectedWorkOrder(wo);
                            setShowDetailModal(true);
                          }}
                          className="p-2 bg-blue-500/20 text-blue-400 rounded-lg hover:bg-blue-500/30"
                          title="View Details"
                        >
                          <FileText className="w-5 h-5" />
                        </button>
                        <button
                          onClick={() => {
                            setEditingWorkOrder(wo);
                            setNewWorkOrder(wo);
                            setShowCreateModal(true);
                          }}
                          className="p-2 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600"
                          title="Edit"
                        >
                          <Edit2 className="w-5 h-5" />
                        </button>
                        <button
                          onClick={() => {
                            if (confirm('Delete this work order?')) {
                              deleteWorkOrder(wo.id);
                            }
                          }}
                          className="p-2 bg-red-500/20 text-red-400 rounded-lg hover:bg-red-500/30"
                          title="Delete"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
              
              {filteredWorkOrders.length === 0 && (
                <div className="text-center py-12 text-slate-500">
                  <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No work orders found</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Service Alerts Tab */}
        {activeTab === 'auto-generate' && (
          <div className="space-y-4">
            <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
              <div className="flex items-center gap-3 mb-4">
                <AlertTriangle className="w-5 h-5 text-orange-400" />
                <h3 className="font-semibold text-white">Component Service Alerts</h3>
                <span className="px-2 py-0.5 bg-orange-500/20 text-orange-400 rounded text-sm">
                  {serviceAlerts.length} items need attention
                </span>
              </div>
              <p className="text-sm text-slate-400 mb-4">
                These components have reached or exceeded their service intervals. Click "Generate Work Order" to create a work order with suggested parts.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              {serviceAlerts.map(alert => {
                const existingWO = workOrders.find(wo => wo.relatedComponent === alert.id && wo.status !== 'Completed');
                
                return (
                  <div
                    key={alert.id}
                    className={`bg-slate-800/50 rounded-xl border p-4 ${getUrgencyColor(alert.urgency)}`}
                  >
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-2">
                        {alert.parentType === 'engine' && <Zap className="w-5 h-5 text-orange-400" />}
                        {alert.parentType === 'head' && <Settings className="w-5 h-5 text-blue-400" />}
                        {alert.parentType === 'supercharger' && <Wind className="w-5 h-5 text-purple-400" />}
                        {alert.parentType === 'maintenance' && <Wrench className="w-5 h-5 text-yellow-400" />}
                        <span className={`px-2 py-0.5 rounded text-xs font-medium uppercase ${getUrgencyColor(alert.urgency)}`}>
                          {alert.urgency}
                        </span>
                      </div>
                      <span className="text-xs text-slate-500">{alert.serviceType}</span>
                    </div>
                    
                    <h4 className="text-white font-medium mb-1">{alert.componentName}</h4>
                    <p className="text-sm text-slate-400 mb-3">{alert.parentName}</p>
                    
                    <div className="flex items-center gap-4 text-sm text-slate-400 mb-4">
                      <span>{alert.passCount} passes</span>
                      <span>Interval: {alert.interval}</span>
                    </div>
                    
                    {alert.suggestedParts.length > 0 && (
                      <div className="mb-4">
                        <p className="text-xs text-slate-500 mb-2">Suggested Parts:</p>
                        <div className="flex flex-wrap gap-1">
                          {alert.suggestedParts.slice(0, 3).map(partId => {
                            const part = partsInventory.find(p => p.id === partId);
                            return part ? (
                              <span key={partId} className="px-2 py-0.5 bg-slate-700 text-slate-300 rounded text-xs">
                                {part.partNumber}
                              </span>
                            ) : null;
                          })}
                        </div>
                      </div>
                    )}
                    
                    {existingWO ? (
                      <div className="flex items-center gap-2 text-sm text-green-400">
                        <CheckCircle2 className="w-4 h-4" />
                        Work order exists: {existingWO.id}
                      </div>
                    ) : (
                      <button
                        onClick={() => generateWorkOrderFromAlert(alert)}
                        className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg font-medium hover:bg-orange-600 transition-colors"
                      >
                        <Plus className="w-4 h-4" />
                        Generate Work Order
                      </button>
                    )}
                  </div>
                );
              })}
              
              {serviceAlerts.length === 0 && (
                <div className="col-span-full text-center py-12 text-slate-500">
                  <CheckCircle2 className="w-12 h-12 mx-auto mb-4 text-green-500 opacity-50" />
                  <p>All components are within service intervals</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Parts Needed Tab */}
        {activeTab === 'parts' && (
          <div className="space-y-4">
            <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
              <h3 className="font-semibold text-white mb-4 flex items-center gap-2">
                <ShoppingCart className="w-5 h-5 text-orange-400" />
                Parts Required for Open Work Orders
              </h3>
              
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="text-left text-slate-400 text-sm border-b border-slate-700">
                      <th className="pb-3 pr-4">Part</th>
                      <th className="pb-3 pr-4">Part Number</th>
                      <th className="pb-3 pr-4">Work Order</th>
                      <th className="pb-3 pr-4">Qty Needed</th>
                      <th className="pb-3 pr-4">In Stock</th>
                      <th className="pb-3 pr-4">Unit Cost</th>
                      <th className="pb-3">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {workOrders
                      .filter(wo => wo.status !== 'Completed' && wo.status !== 'Cancelled')
                      .flatMap(wo => (Array.isArray(wo.parts) ? wo.parts : []).map(part => ({ ...part, workOrderId: wo.id, workOrderTitle: wo.title })))
                      .map((part, index) => {
                        const inventoryPart = partsInventory.find(p => p.partNumber === part.partNumber);
                        const inStock = inventoryPart?.onHand || 0;
                        const hasStock = inStock >= (part.quantity || 0);
                        
                        return (
                          <tr key={`${part.workOrderId}-${index}`} className="border-b border-slate-700/50">
                            <td className="py-3 pr-4 text-white">{part.name}</td>
                            <td className="py-3 pr-4 text-slate-400 font-mono text-sm">{part.partNumber}</td>
                            <td className="py-3 pr-4 text-slate-400 text-sm">{part.workOrderId}</td>
                            <td className="py-3 pr-4 text-white">{part.quantity}</td>
                            <td className="py-3 pr-4">
                              <span className={hasStock ? 'text-green-400' : 'text-red-400'}>
                                {inStock}
                              </span>
                            </td>
                            <td className="py-3 pr-4 text-white">${(part.cost || 0).toLocaleString()}</td>
                            <td className="py-3">
                              {hasStock ? (
                                <span className="px-2 py-0.5 bg-green-500/20 text-green-400 rounded text-xs">
                                  Available
                                </span>
                              ) : (
                                <span className="px-2 py-0.5 bg-red-500/20 text-red-400 rounded text-xs">
                                  Order Needed
                                </span>
                              )}
                            </td>
                          </tr>
                        );
                      })}
                  </tbody>
                </table>
              </div>
              
              {workOrders.filter(wo => wo.status !== 'Completed' && wo.status !== 'Cancelled').flatMap(wo => Array.isArray(wo.parts) ? wo.parts : []).length === 0 && (
                <div className="text-center py-8 text-slate-500">
                  <Package className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No parts needed for current work orders</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Create/Edit Work Order Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-slate-800 rounded-xl max-w-2xl w-full p-6 border border-slate-700 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-white">
                {editingWorkOrder ? 'Edit Work Order' : 'Create Work Order'}
              </h3>
              <button onClick={() => setShowCreateModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              {/* Car Assignment */}
              <CarDropdown
                value={newWorkOrder.car_id || ''}
                onChange={(carId) => setNewWorkOrder({ ...newWorkOrder, car_id: carId })}
                label="Assign to Car"
              />


              <div>
                <label className="block text-sm text-slate-400 mb-1">Title *</label>
                <input
                  type="text"
                  value={newWorkOrder.title}
                  onChange={(e) => setNewWorkOrder({ ...newWorkOrder, title: e.target.value })}
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  placeholder="e.g., Replace Main Bearings"
                />
              </div>


              <div>
                <label className="block text-sm text-slate-400 mb-1">Description</label>
                <textarea
                  value={newWorkOrder.description}
                  onChange={(e) => setNewWorkOrder({ ...newWorkOrder, description: e.target.value })}
                  rows={3}
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Category</label>
                  <select
                    value={newWorkOrder.category}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, category: e.target.value })}
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  >
                    <option value="General">General</option>
                    <option value="Engine">Engine</option>
                    <option value="Cylinder Heads">Cylinder Heads</option>
                    <option value="Supercharger">Supercharger</option>
                    <option value="Drivetrain">Drivetrain</option>
                    <option value="Ty-Drive">Ty-Drive</option>
                    <option value="Quick Drive">Quick Drive</option>
                    <option value="Transmission">Transmission</option>
                    <option value="Suspension">Suspension</option>
                    <option value="Brakes">Brakes</option>
                    <option value="Fluids">Fluids</option>
                    <option value="Electronics">Electronics</option>
                    <option value="Safety">Safety</option>
                    <option value="Body">Body</option>
                  </select>

                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Priority</label>
                  <select
                    value={newWorkOrder.priority}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, priority: e.target.value as WorkOrder['priority'] })}

                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                    <option value="Critical">Critical</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Status</label>
                  <select
                    value={newWorkOrder.status}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, status: e.target.value as WorkOrder['status'] })}
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  >

                    <option value="Open">Open</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Pending Parts">Pending Parts</option>
                    <option value="Completed">Completed</option>
                    <option value="Cancelled">Cancelled</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Assigned To</label>
                  <select
                    value={newWorkOrder.assignedTo}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, assignedTo: e.target.value })}
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  >
                    <option value="">Select...</option>
                    {teamMembers.map(member => (
                      <option key={member.id} value={member.name}>{member.name}</option>
                    ))}
                    <option value="Unassigned">Unassigned</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm text-slate-400 mb-1">Vendor</label>
                <select
                  value={woVendor}
                  onChange={(e) => setWoVendor(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                >
                  <option value="">Select vendor...</option>
                  {vendorsList.map(v => (
                    <option key={v.id} value={v.name}>{v.name} ({v.category})</option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Due Date</label>
                  <DateInputDark
                    value={newWorkOrder.dueDate}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, dueDate: e.target.value })}
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  />

                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Estimated Hours</label>
                  <input
                    type="number"
                    step="0.5"
                    value={newWorkOrder.estimatedHours}
                    onChange={(e) => setNewWorkOrder({ ...newWorkOrder, estimatedHours: parseFloat(e.target.value) || 0 })}
                    className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                  />
                </div>
              </div>

              {/* Parts Section */}
              <div className="border-t border-slate-700 pt-4">
                <h4 className="font-medium text-white mb-3 flex items-center gap-2">
                  <Package className="w-4 h-4 text-orange-400" />
                  Parts Required
                </h4>

                {/* Mode Toggle */}
                <div className="flex gap-2 mb-3">
                  <button
                    onClick={() => setPartsEntryMode('inventory')}
                    className={`flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                      partsEntryMode === 'inventory'
                        ? 'bg-orange-500 text-white'
                        : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
                    }`}
                  >
                    <Package className="w-4 h-4" />
                    Select from Inventory
                  </button>
                  <button
                    onClick={() => setPartsEntryMode('manual')}
                    className={`flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                      partsEntryMode === 'manual'
                        ? 'bg-orange-500 text-white'
                        : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
                    }`}
                  >
                    <Edit2 className="w-4 h-4" />
                    Manual Entry
                  </button>
                </div>

                {/* Inventory Selection Mode */}
                {partsEntryMode === 'inventory' && (
                  <div className="flex gap-2 mb-3">
                    <select
                      value={selectedInventoryPart}
                      onChange={(e) => setSelectedInventoryPart(e.target.value)}
                      className="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                    >
                      <option value="">Select from inventory...</option>
                      {partsInventory.map(part => (
                        <option key={part.id} value={part.id}>
                          {part.partNumber} - {part.description} (${part.unitCost}) [{part.onHand} in stock]
                        </option>
                      ))}
                    </select>
                    <input
                      type="number"
                      min="1"
                      value={newPart.quantity}
                      onChange={(e) => setNewPart({ ...newPart, quantity: parseInt(e.target.value) || 1 })}
                      className="w-20 bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                      placeholder="Qty"
                    />
                    <button
                      onClick={handleAddPart}
                      disabled={!selectedInventoryPart}
                      className="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed"
                      title="Add part from inventory"
                    >
                      <Plus className="w-4 h-4" />
                    </button>
                  </div>
                )}

                {/* Manual Entry Mode */}
                {partsEntryMode === 'manual' && (
                  <div className="space-y-2 mb-3 p-3 bg-slate-900/50 rounded-lg border border-slate-700/50">
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <label className="block text-xs text-slate-500 mb-1">Part Name *</label>
                        <input
                          type="text"
                          value={newPart.name}
                          onChange={(e) => setNewPart({ ...newPart, name: e.target.value })}
                          className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                          placeholder="e.g., Main Bearing Set"
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-slate-500 mb-1">Part Number</label>
                        <input
                          type="text"
                          value={newPart.partNumber}
                          onChange={(e) => setNewPart({ ...newPart, partNumber: e.target.value })}
                          className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                          placeholder="e.g., MB-4340"
                        />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <label className="block text-xs text-slate-500 mb-1">Quantity</label>
                        <input
                          type="number"
                          min="1"
                          value={newPart.quantity}
                          onChange={(e) => setNewPart({ ...newPart, quantity: parseInt(e.target.value) || 1 })}
                          className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                          placeholder="1"
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-slate-500 mb-1">Unit Cost ($)</label>
                        <input
                          type="number"
                          min="0"
                          step="0.01"
                          value={newPart.cost || ''}
                          onChange={(e) => setNewPart({ ...newPart, cost: parseFloat(e.target.value) || 0 })}
                          className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"
                          placeholder="0.00"
                        />
                      </div>
                    </div>
                    <button
                      onClick={() => {
                        if (newPart.name.trim()) {
                          setNewWorkOrder({
                            ...newWorkOrder,
                            parts: [...newWorkOrder.parts, {
                              name: newPart.name.trim(),
                              partNumber: newPart.partNumber.trim() || `MANUAL-${Date.now().toString(36).toUpperCase()}`,
                              quantity: newPart.quantity || 1,
                              cost: newPart.cost || 0
                            }]
                          });
                          setNewPart({ name: '', partNumber: '', quantity: 1, cost: 0 });
                        }
                      }}
                      disabled={!newPart.name.trim()}
                      className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium"
                    >
                      <Plus className="w-4 h-4" />
                      Add Manual Part
                    </button>
                  </div>
                )}

                {/* Parts List */}
                {(newWorkOrder.parts || []).length > 0 && (
                  <div className="space-y-2">
                    {(newWorkOrder.parts || []).map((part, index) => {
                      const isInInventory = partsInventory.some(
                        p => p.partNumber === part.partNumber || p.description.toLowerCase() === part.name.toLowerCase()
                      );
                      const partKey = `${part.partNumber || ''}-${part.name}`;
                      const wasAddedToInventory = addedToInventoryParts.has(partKey);

                      return (
                        <div key={index} className="flex items-center justify-between p-2 bg-slate-900/50 rounded-lg">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <span className="text-white text-sm truncate">{part.name}</span>
                              {isInInventory ? (
                                <span className="px-1.5 py-0.5 bg-green-500/20 text-green-400 rounded text-[10px] font-medium whitespace-nowrap flex-shrink-0">
                                  IN INVENTORY
                                </span>
                              ) : (
                                <span className="px-1.5 py-0.5 bg-yellow-500/20 text-yellow-400 rounded text-[10px] font-medium whitespace-nowrap flex-shrink-0">
                                  MANUAL
                                </span>
                              )}
                            </div>
                            <span className="text-slate-500 text-xs">{part.partNumber}</span>
                          </div>
                          <div className="flex items-center gap-2 ml-2 flex-shrink-0">
                            <span className="text-slate-400 text-sm">x{part.quantity}</span>
                            <span className="text-white text-sm">${((part.cost || 0) * (part.quantity || 0)).toLocaleString()}</span>
                            {!isInInventory && !wasAddedToInventory && (
                              <button
                                onClick={() => handleAddPartToInventory(part)}
                                className="flex items-center gap-1 px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs hover:bg-blue-500/30 transition-colors whitespace-nowrap"
                                title="Add this part to Parts Inventory"
                              >
                                <PackagePlus className="w-3 h-3" />
                                Add to Inventory
                              </button>
                            )}
                            {!isInInventory && wasAddedToInventory && (
                              <span className="flex items-center gap-1 px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs whitespace-nowrap">
                                <CheckCircle2 className="w-3 h-3" />
                                Added
                              </span>
                            )}
                            <button
                              onClick={() => handleRemovePart(index)}
                              className="text-red-400 hover:text-red-300"
                            >
                              <X className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              <div>
                <label className="block text-sm text-slate-400 mb-1">Notes</label>
                <textarea
                  value={newWorkOrder.notes}
                  onChange={(e) => setNewWorkOrder({ ...newWorkOrder, notes: e.target.value })}
                  rows={2}
                  className="w-full bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-white"
                />
              </div>

              {/* Cost Summary */}
              <div className="bg-slate-900/50 rounded-lg p-4">
                <h4 className="font-medium text-white mb-3 flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-green-400" />
                  Cost Estimate
                </h4>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Parts Cost:</span>
                    <span className="text-white">${(newWorkOrder.parts || []).reduce((sum, p) => sum + ((p.cost || 0) * (p.quantity || 0)), 0).toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Labor Cost ({newWorkOrder.estimatedHours}h @ ${DEFAULT_HOURLY_RATE}/hr):</span>
                    <span className="text-white">${(newWorkOrder.estimatedHours * DEFAULT_HOURLY_RATE).toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between pt-2 border-t border-slate-700 font-medium">
                    <span className="text-white">Total Estimated:</span>
                    <span className="text-green-400">
                      ${((newWorkOrder.parts || []).reduce((sum, p) => sum + ((p.cost || 0) * (p.quantity || 0)), 0) + (newWorkOrder.estimatedHours * DEFAULT_HOURLY_RATE)).toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowCreateModal(false)}
                className="flex-1 px-4 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveWorkOrder}
                disabled={!newWorkOrder.title}
                className="flex-1 px-4 py-2 bg-orange-500 text-white rounded-lg font-medium hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {editingWorkOrder ? 'Save Changes' : 'Create Work Order'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Work Order Detail Modal */}
      {showDetailModal && selectedWorkOrder && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-slate-800 rounded-xl max-w-2xl w-full p-6 border border-slate-700 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <span className="text-slate-500 font-mono">{selectedWorkOrder.id}</span>
                  <span className={`px-2 py-0.5 rounded text-xs font-medium border ${getStatusColor(selectedWorkOrder.status)}`}>
                    {selectedWorkOrder.status}
                  </span>
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${getPriorityColor(selectedWorkOrder.priority)}`}>
                    {selectedWorkOrder.priority}
                  </span>
                </div>
                <h3 className="text-xl font-bold text-white">{selectedWorkOrder.title}</h3>
              </div>
              <button onClick={() => setShowDetailModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-6">
              <div>
                <p className="text-slate-300">{selectedWorkOrder.description}</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="bg-slate-900/50 rounded-lg p-3">
                  <p className="text-xs text-slate-500 mb-1">Assigned To</p>
                  <p className="text-white">{selectedWorkOrder.assignedTo}</p>
                </div>
                <div className="bg-slate-900/50 rounded-lg p-3">
                  <p className="text-xs text-slate-500 mb-1">Category</p>
                  <p className="text-white">{selectedWorkOrder.category}</p>
                </div>
                <div className="bg-slate-900/50 rounded-lg p-3">
                  <p className="text-xs text-slate-500 mb-1">Created</p>
                  <p className="text-white">{selectedWorkOrder.createdDate}</p>
                </div>
                <div className="bg-slate-900/50 rounded-lg p-3">
                  <p className="text-xs text-slate-500 mb-1">Due Date</p>
                  <p className="text-white">{selectedWorkOrder.dueDate}</p>
                </div>
              </div>

              {/* Labor Tracking */}
              <div className="border-t border-slate-700 pt-4">
                <h4 className="font-medium text-white mb-3 flex items-center gap-2">
                  <Clock className="w-4 h-4 text-cyan-400" />
                  Labor Tracking
                </h4>
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-slate-900/50 rounded-lg p-3">
                    <p className="text-xs text-slate-500 mb-1">Estimated Hours</p>
                    <p className="text-white text-lg">{selectedWorkOrder.estimatedHours}h</p>
                  </div>
                  <div className="bg-slate-900/50 rounded-lg p-3">
                    <p className="text-xs text-slate-500 mb-1">Actual Hours</p>
                    <p className="text-white text-lg">{selectedWorkOrder.actualHours?.toFixed(1) || '0'}h</p>
                  </div>
                </div>
                
                {selectedWorkOrder.status !== 'Completed' && selectedWorkOrder.status !== 'Cancelled' && (
                  <div className="mt-3 flex gap-2">
                    {activeLaborEntry?.workOrderId === selectedWorkOrder.id ? (
                      <button
                        onClick={() => stopLabor('')}
                        className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-red-500 text-white rounded-lg font-medium hover:bg-red-600"
                      >
                        <PauseCircle className="w-4 h-4" />
                        Stop Timer
                      </button>
                    ) : !activeLaborEntry ? (
                      <button
                        onClick={() => startLabor(selectedWorkOrder.id, teamMembers[0]?.name || 'Technician')}
                        className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-green-500 text-white rounded-lg font-medium hover:bg-green-600"
                      >
                        <PlayCircle className="w-4 h-4" />
                        Start Labor Timer
                      </button>
                    ) : null}
                    {selectedWorkOrder.status === 'In Progress' && (
                      <button
                        onClick={() => {
                          handleCompleteWorkOrder(selectedWorkOrder.id);
                          setShowDetailModal(false);
                        }}
                        className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700"
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        Complete Work Order
                      </button>
                    )}
                  </div>
                )}
              </div>

              {/* Parts */}
              {(Array.isArray(selectedWorkOrder.parts) ? selectedWorkOrder.parts : []).length > 0 && (
                <div className="border-t border-slate-700 pt-4">
                  <h4 className="font-medium text-white mb-3 flex items-center gap-2">
                    <Package className="w-4 h-4 text-orange-400" />
                    Parts ({(Array.isArray(selectedWorkOrder.parts) ? selectedWorkOrder.parts : []).length})
                  </h4>
                  <div className="space-y-2">
                    {(Array.isArray(selectedWorkOrder.parts) ? selectedWorkOrder.parts : []).map((part, index) => {
                      const inventoryPart = partsInventory.find(p => p.partNumber === part.partNumber);
                      const isInInventory = !!inventoryPart || partsInventory.some(p => p.description.toLowerCase() === part.name.toLowerCase());
                      const inStock = inventoryPart?.onHand || 0;
                      const partKey = `${part.partNumber || ''}-${part.name}`;
                      const wasAddedToInventory = addedToInventoryParts.has(partKey);
                      
                      return (
                        <div key={index} className="flex items-center justify-between p-3 bg-slate-900/50 rounded-lg">
                          <div>
                            <div className="flex items-center gap-2">
                              <p className="text-white">{part.name}</p>
                              {isInInventory ? (
                                <span className="px-1.5 py-0.5 bg-green-500/20 text-green-400 rounded text-[10px] font-medium">
                                  IN INVENTORY
                                </span>
                              ) : (
                                <span className="px-1.5 py-0.5 bg-yellow-500/20 text-yellow-400 rounded text-[10px] font-medium">
                                  MANUAL
                                </span>
                              )}
                            </div>
                            <p className="text-xs text-slate-500">{part.partNumber}</p>
                          </div>
                          <div className="flex items-center gap-3">
                            <span className={`text-sm ${inStock >= (part.quantity || 0) ? 'text-green-400' : 'text-red-400'}`}>
                              {inStock} in stock
                            </span>
                            <span className="text-slate-400">x{part.quantity}</span>
                            <span className="text-white font-medium">${((part.cost || 0) * (part.quantity || 0)).toLocaleString()}</span>
                            {!isInInventory && !wasAddedToInventory && (
                              <button
                                onClick={() => handleAddPartToInventory(part)}
                                className="flex items-center gap-1 px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs hover:bg-blue-500/30 transition-colors whitespace-nowrap"
                                title="Add this part to Parts Inventory"
                              >
                                <PackagePlus className="w-3 h-3" />
                                Add to Inventory
                              </button>
                            )}
                            {!isInInventory && wasAddedToInventory && (
                              <span className="flex items-center gap-1 px-2 py-1 bg-green-500/20 text-green-400 rounded text-xs whitespace-nowrap">
                                <CheckCircle2 className="w-3 h-3" />
                                Added
                              </span>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Cost Summary */}
              <div className="border-t border-slate-700 pt-4">
                <h4 className="font-medium text-white mb-3 flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-green-400" />
                  Cost Summary
                </h4>
                <div className="bg-slate-900/50 rounded-lg p-4">
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-slate-400">Parts Cost:</span>
                      <span className="text-white">${(Array.isArray(selectedWorkOrder.parts) ? selectedWorkOrder.parts : []).reduce((sum, p) => sum + ((p.cost || 0) * (p.quantity || 0)), 0).toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-400">Estimated Labor:</span>
                      <span className="text-white">${((selectedWorkOrder.estimatedHours || 0) * DEFAULT_HOURLY_RATE).toLocaleString()}</span>
                    </div>
                    {selectedWorkOrder.actualHours !== undefined && (
                      <div className="flex justify-between">
                        <span className="text-slate-400">Actual Labor:</span>
                        <span className="text-white">${(selectedWorkOrder.actualHours * DEFAULT_HOURLY_RATE).toLocaleString()}</span>
                      </div>
                    )}
                    <div className="flex justify-between pt-2 border-t border-slate-700 font-medium">
                      <span className="text-white">Total:</span>
                      <span className="text-green-400">
                        ${((Array.isArray(selectedWorkOrder.parts) ? selectedWorkOrder.parts : []).reduce((sum, p) => sum + ((p.cost || 0) * (p.quantity || 0)), 0) + 
                           ((selectedWorkOrder.actualHours || selectedWorkOrder.estimatedHours || 0) * DEFAULT_HOURLY_RATE)).toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {selectedWorkOrder.notes && (
                <div className="border-t border-slate-700 pt-4">
                  <h4 className="font-medium text-white mb-2">Notes</h4>
                  <p className="text-slate-400 text-sm">{selectedWorkOrder.notes}</p>
                </div>
              )}
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowDetailModal(false)}
                className="flex-1 px-4 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600"
              >
                Close
              </button>
              <button
                onClick={() => {
                  setShowDetailModal(false);
                  setEditingWorkOrder(selectedWorkOrder);
                  setNewWorkOrder(selectedWorkOrder);
                  setShowCreateModal(true);
                }}
                className="flex-1 px-4 py-2 bg-orange-500 text-white rounded-lg font-medium hover:bg-orange-600"
              >
                Edit Work Order
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Usage History Modal for Work Order */}
      {showUsageHistoryModal && selectedWorkOrderForHistory && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-slate-800 rounded-xl max-w-3xl w-full p-6 border border-slate-700 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-white flex items-center gap-2">
                <History className="w-6 h-6 text-purple-400" />
                Parts Usage History - {selectedWorkOrderForHistory}
              </h3>
              <button onClick={() => setShowUsageHistoryModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-3">
              {getWorkOrderUsageHistory(selectedWorkOrderForHistory).map(record => (
                <div key={record.id} className="bg-slate-900/50 rounded-lg p-4 border border-slate-700/50">
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <ArrowDownCircle className="w-4 h-4 text-green-400" />
                        <span className="text-orange-400 font-mono text-sm">{record.partNumber}</span>
                        <span className="px-2 py-0.5 bg-green-500/20 text-green-400 rounded text-xs capitalize">
                          {record.action}
                        </span>
                      </div>
                      <p className="text-white font-medium">{record.partDescription}</p>
                      <p className="text-sm text-slate-400">{record.installedOn}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-white font-medium">${(record.cost + (record.laborCost || 0)).toLocaleString()}</p>
                      <p className="text-xs text-slate-500">{record.date}</p>
                    </div>
                  </div>
                  {record.notes && (
                    <p className="text-sm text-slate-400 mt-2 pt-2 border-t border-slate-700/50">{record.notes}</p>
                  )}
                </div>
              ))}

              {getWorkOrderUsageHistory(selectedWorkOrderForHistory).length === 0 && (
                <div className="text-center py-8 text-slate-500">
                  <History className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No usage records found for this work order</p>
                </div>
              )}
            </div>

            <div className="flex justify-end mt-6">
              <button
                onClick={() => setShowUsageHistoryModal(false)}
                className="px-4 py-2 bg-slate-700 text-white rounded-lg hover:bg-slate-600"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

export default WorkOrderSystem;
